let session=JSON.parse(localStorage.getItem('chs')||'null'),watch=null,state=null,pollTimer=null;const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const toast=t=>{const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2800)};
async function api(path,data={},method='POST'){let url='/api/'+path,opts={method,headers:{'Content-Type':'application/json'}};if(method==='GET'){url+='?'+new URLSearchParams(data)}else opts.body=JSON.stringify(data);const r=await fetch(url,opts),j=await r.json();if(!r.ok){const e=new Error(j.error);e.data=j;throw e}return j}
const creds=x=>({code:session.code,userId:session.userId,...x});
const profile=()=>({name:$('#name').value.trim()||'Spieler',vehicle:$('#vehicle').value.trim()||'Unbekannt',color:$('#color').value.trim()||'Unbekannt',mode:$('#mode').value});
async function create(){try{const j=await api('create',{...profile(),lobbyName:$('#lname').value,radius:+$('#radius').value,duration:+$('#duration').value,headstart:+$('#headstart').value,escape:+$('#escape').value});save(j);show()}catch(e){toast(e.message)}}
async function join(){try{const j=await api('join',{...profile(),code:$('#code').value});save(j);show()}catch(e){toast(e.message)}}
function save(j){session={code:j.lobby.code,userId:j.userId};localStorage.setItem('chs',JSON.stringify(session))}
function show(){$('#home').classList.add('hidden');$('#game').classList.remove('hidden');poll()}
async function poll(){clearTimeout(pollTimer);if(!session)return;try{state=await api('state',creds(),'GET');render()}catch(e){toast(e.message);if(e.message.includes('Session'))reset()}pollTimer=setTimeout(poll,1000)}
function fmt(sec){sec=Math.max(0,Math.ceil(sec));return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
function render(){const l=state.lobby,me=l.me,t=state.serverTime;$('#lobbyName').textContent=l.name;$('#lobbyCode').textContent=l.code;$('#state').textContent=l.state;$('#count').textContent=`${l.players.length}`;$('#role').textContent=me.role==='SEEKER'?'🔎 SUCHER':me.role==='HIDER'?'👤 VERSTECKER':'OFFEN';$('#driverWarning').classList.toggle('hidden',me.mode!=='DRIVER');let end=l.state==='COUNTDOWN'?l.countdownEndsAt:l.state==='HEADSTART'?l.headstartEndsAt:l.endsAt;$('#timer').textContent=end?fmt((end-t)/1000):'–';$('#ready').textContent=me.ready?'✓ BEREIT':'BEREIT';$('#ready').classList.toggle('active',me.ready);$('#ready').classList.toggle('hidden',l.state!=='LOBBY');$('#setStart').classList.toggle('hidden',l.hostId!==me.id||!me.hasLocation||l.state!=='LOBBY');$('#start').classList.toggle('hidden',l.hostId!==me.id||l.state!=='LOBBY'||l.players.length<2);$('#gpsDot').classList.toggle('on',me.hasLocation);
 const pr=state.proximity;let txt='GPS aktiv. Warte auf verwertbare Gegnerdaten.';if(pr){txt=pr.level==='VERY_CLOSE'?`⚠️ EXTREM NAH · ca. ${pr.distance} m`:pr.level==='CLOSE'?`⚠️ SEHR NAH · ca. ${pr.distance} m`:pr.level==='NEAR'?`⚠️ JEMAND NÄHERT SICH · ca. ${pr.distance} m`:`Kein Gegner in direkter Nähe · ca. ${pr.distance} m`;$('#enemyDot').classList.remove('hidden');const px=Math.min(115,25+pr.distance/2);$('#enemyDot').style.transform=`translate(${Math.cos(t/700)*px}px,${Math.sin(t/700)*px}px)`}else $('#enemyDot').classList.add('hidden');$('#proximity').textContent=txt;$('#proximity').classList.toggle('hot',!!pr&&pr.distance<50);
 const escLeft=Math.ceil((state.escapeUntil-t)/1000);$('#escapeBox').classList.toggle('hidden',!(escLeft>0&&me.role==='HIDER'));$('#escapeTimer').textContent=Math.max(0,escLeft);
 $('#players').innerHTML=l.players.map(p=>`<div class="player ${p.found?'found':''}"><div class="avatar">${p.role==='SEEKER'?'🔎':p.role==='HIDER'?'👤':'🚘'}</div><div class="pdata"><b>${esc(p.name)} ${p.id===l.hostId?'<em>HOST</em>':''}</b><small>${esc(p.vehicle)} · ${esc(p.color)}</small><small>${p.connected?'● Online':'○ Reconnect…'} · Lv. ${p.level}</small></div><div>${p.ready?'✓':''}${p.found?' FOUND':''}</div></div>`).join('');
 const targets=l.players.filter(p=>p.role==='HIDER'&&!p.found),canFind=me.role==='SEEKER'&&l.state==='ACTIVE';$('#targets').classList.toggle('hidden',!canFind);$('#targetButtons').innerHTML=targets.map(p=>`<button class="danger" onclick="found('${p.id}')">🚘 ${esc(p.vehicle)} · ${esc(p.color)}</button>`).join('');const cd=Math.ceil((state.cooldownUntil-t)/1000);$('#cooldown').textContent=cd>0?`Nächster Fundversuch in ${fmt(cd)}`:'';
 $('#result').classList.toggle('hidden',l.state!=='RESULT');if(l.state==='RESULT'){const win=l.result?.seekersWin;$('#resultTitle').textContent=win?'SUCHER GEWINNEN':'VERSTECKER GEWINNEN';$('#resultText').textContent=`${l.result?.found||0} von ${l.result?.totalHiders||0} Versteckern gefunden.`;$('#xpGain').textContent=me.role==='SEEKER'?100+(l.result?.found||0)*80:(me.found?140:280);$('#rematch').classList.toggle('hidden',l.hostId!==me.id)} }
function gps(){if(!navigator.geolocation)return toast('Dieses Gerät unterstützt keine Standortabfrage.');if(watch!==null)return toast('GPS läuft bereits.');watch=navigator.geolocation.watchPosition(async q=>{try{await api('location',creds({lat:q.coords.latitude,lng:q.coords.longitude,accuracy:q.coords.accuracy,altitude:q.coords.altitude,speed:q.coords.speed}))}catch{}},e=>toast('GPS: '+e.message),{enableHighAccuracy:true,maximumAge:2000,timeout:12000});$('#gps').textContent='GPS AKTIV ✓';toast('Standortübertragung gestartet')}
async function ready(){try{await api('ready',creds({ready:!state.lobby.me.ready}))}catch(e){toast(e.message)}}async function setStart(){try{await api('startpoint',creds());toast('📍 Startpunkt gesetzt')}catch(e){toast(e.message)}}async function start(){try{await api('start',creds());toast('Countdown gestartet')}catch(e){toast(e.message)}}async function found(targetId){try{const j=await api('found',creds({targetId}));toast(`✅ FUND BESTÄTIGT · ${j.distance} m`)}catch(e){toast(`❌ ${e.message}${e.data?.distance!=null?' · '+e.data.distance+' m':''}`)}}async function rematch(){try{await api('rematch',creds())}catch(e){toast(e.message)}}async function leave(){try{await api('leave',creds())}catch{}reset()}function reset(){if(watch!==null)navigator.geolocation.clearWatch(watch);localStorage.removeItem('chs');location.reload()}
$('#create').onclick=create;$('#join').onclick=join;$('#gps').onclick=gps;$('#ready').onclick=ready;$('#setStart').onclick=setStart;$('#start').onclick=start;$('#rematch').onclick=rematch;$('#leave').onclick=leave;if(session)show();
