'use strict';
(function(){
 const categories={dangerous_driving:'Gefährliches Fahren',harassment:'Belästigung',cheating:'Manipulation / falscher Standort',privacy:'Privatsphäre',other:'Sonstiger Regelverstoß'};
 const statuses={open:'Offen',in_review:'In Prüfung',resolved:'Erledigt',dismissed:'Zurückgewiesen'};
 const options=values=>Object.entries(values).map(([value,label])=>`<option value="${esc(value)}">${esc(label)}</option>`).join('');
 function dialog(id,title){document.getElementById(id)?.remove();const d=document.createElement('dialog');d.id=id;d.className='productDialog betaDialog';d.innerHTML=`<button class="dialogClose" aria-label="Schließen">×</button><h2>${esc(title)}</h2><div data-content></div><p role="alert" class="accountError"></p>`;d.querySelector('button').onclick=()=>d.close();document.body.append(d);return d;}
 function bind(d,form,work){let busy=false;form.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;const controls=[...form.querySelectorAll('button,input,select,textarea')];controls.forEach(c=>c.disabled=true);try{await work(form);}catch(error){if(d.isConnected)d.querySelector('[role=alert]').textContent=error.message;}finally{busy=false;controls.forEach(c=>c.disabled=false);}});}
 function report(player){const d=dialog('reportDialog','SPIELER MELDEN');d.querySelector('[data-content]').innerHTML=`<p>${esc(player.name)}</p><form><label>Kategorie<select name="category">${options(categories)}</select></label><label>Kommentar (freiwillig)<textarea name="comment" maxlength="500"></textarea></label><button>MELDUNG SENDEN</button></form>`;bind(d,d.querySelector('form'),async f=>{await api('report',gameCredentials({targetId:player.id,category:f.elements.category.value,comment:f.elements.comment.value}));toast('Meldung gespeichert.');d.close();d.remove();});d.showModal();}
 function onboard(account){const d=dialog('onboardingDialog','SO SPIELEN WIR SICHER');d.querySelector('.dialogClose').remove();d.addEventListener('cancel',e=>e.preventDefault());const rules=['Teilnahme ab 18 Jahren; Verkehrsregeln gelten immer.','Keine Rennen, Verfolgungsfahrten oder riskanten Manöver.','Fahrer bedienen die App erst nach sicherem Parken; Beifahrer können unterstützen.','Nur erlaubte öffentliche Orte; keine Garagen, Parkhäuser oder privaten Grundstücke als Versteck.','Alle treffen sich mit zuverlässigem GPS innerhalb von 50 m.','Der Standardradius beträgt 500 m; der Host legt ihn vor dem Start fest.','Sucher warten während des Vorsprungs sicher und ohne Beobachten am Wartepunkt.','Verstecker bleiben im Radius; länger als zwei Minuten außerhalb führt zum Ausscheiden.','Ein Fund braucht den vorgesehenen GPS-Nachweis; keine körperliche Konfrontation.','Du kannst melden, blockieren und jederzeit die Runde verlassen.','GPS dient dem laufenden Spiel. Gegner sehen keine freie Standortverfolgung; Moderation erhält keine Koordinaten.'];d.querySelector('[data-content]').innerHTML=`<ol>${rules.map(t=>`<li>${esc(t)}</li>`).join('')}</ol><p>Standortdaten werden nur für Lobby, Spielbereich, Nähe und Fundprüfung verwendet. <a href="/legal/privacy" target="_blank" rel="noopener">Datenschutz</a></p><form><label>Land (freiwillig, für grobe Beta-Auswertung)<select name="country"><option value="">Keine Angabe</option>${options({DE:'Deutschland',AT:'Österreich',CH:'Schweiz',OTHER:'Anderes Land'})}</select></label><label>Bundesland (freiwillig)<select name="region"><option value="">Keine Angabe</option>${options({BW:'Baden-Württemberg',BY:'Bayern',BE:'Berlin',BB:'Brandenburg',HB:'Bremen',HH:'Hamburg',HE:'Hessen',MV:'Mecklenburg-Vorpommern',NI:'Niedersachsen',NW:'Nordrhein-Westfalen',RP:'Rheinland-Pfalz',SL:'Saarland',SN:'Sachsen',ST:'Sachsen-Anhalt',SH:'Schleswig-Holstein',TH:'Thüringen'})}</select></label><label class="betaCheck"><input name="understood" type="checkbox" required> Ich habe die Spielregeln verstanden.</label><button>BESTÄTIGEN UND WEITER</button></form>`;const f=d.querySelector('form');f.elements.region.disabled=true;f.elements.country.onchange=()=>{f.elements.region.disabled=f.elements.country.value!=='DE';if(f.elements.region.disabled)f.elements.region.value='';};const actor=authSession?.user?.id;bind(d,f,async form=>{if(actor!==authSession?.user?.id)throw Error('Bitte neu anmelden.');await api('onboarding',{version:account.onboardingVersion,understood:form.elements.understood.checked,country:form.elements.country.value||null,region:form.elements.country.value==='DE'?form.elements.region.value||null:null});d.remove();await initializeAuth();});d.showModal();}
 async function openAdmin(account){
 const actor=authSession?.user?.id,d=dialog('adminDialog','MODERATION');const permissions=account.permissions||[];const views={reports:'Meldungen',players:'Spieler',lobbies:'Lobbys',stats:'Beta-Auswertung',audit:'Protokoll'};d.querySelector('[data-content]').innerHTML=`<p>Rolle: ${esc(account.role)}. Keine Standortkoordinaten oder privaten Nachrichten.</p><nav class="adminTabs">${Object.entries(views).filter(([k])=>permissions.includes(k)).map(([k,label])=>`<button data-view="${k}">${label}</button>`).join('')}</nav><div data-output></div>`;const out=d.querySelector('[data-output]');let generation=0,page=0,query='',filter='open';const valid=()=>d.isConnected&&actor===authSession?.user?.id;
 function mutation(title,fields,submit,view){const f=document.createElement('form');f.className='betaMutation';f.innerHTML=`<h3>${esc(title)}</h3>${fields}<label>Begründung<textarea name="reason" minlength="5" maxlength="500" required></textarea></label><label class="betaCheck"><input type="checkbox" required> Ziel und Änderung geprüft</label><button>VERBINDLICH SPEICHERN</button><button type="button" data-cancel>ABBRECHEN</button>`;f.querySelector('[data-cancel]').onclick=()=>f.remove();bind(d,f,async form=>{if(!valid())throw Error('Konto wurde gewechselt.');await submit(form);toast('Gespeichert');await show(view);});out.prepend(f);f.scrollIntoView({block:'nearest'});}
 async function show(view){const attempt=++generation;out.textContent='Wird geladen …';d.querySelector('[role=alert]').textContent='';try{const r=await api('admin-'+view,view==='players'?{q:query,page}:view==='reports'?{status:filter,page}:{},'GET');if(!valid()||attempt!==generation)return;
 if(view==='reports'){out.innerHTML=`<label>Status<select data-filter><option value="all">Alle</option>${options(statuses)}</select></label>${r.reports.map((p,i)=>`<article><strong>${esc(categories[p.category]||p.category)} · ${esc(statuses[p.status])}</strong><p>${esc(p.comment)}</p><p>Lobby ${esc(p.lobby_code)} · ${esc(p.created_at)}</p><p>Melder: <code>${esc(p.reporter_id||'gelöscht')}</code><br>Ziel: <code>${esc(p.target_id||'gelöscht')}</code></p><p>${esc(p.resolution)}</p><button data-report="${i}">BEARBEITEN</button></article>`).join('')||'<p>Keine Meldungen.</p>'}`;out.querySelector('[data-filter]').value=filter;out.querySelector('[data-filter]').onchange=e=>{filter=e.target.value;page=0;void show(view);};out.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{const p=r.reports[Number(b.dataset.report)];mutation('Meldung bearbeiten',`<label>Status<select name="status">${options(statuses)}</select></label>`,f=>api('admin-report-update',{id:p.id,status:f.elements.status.value,resolution:f.elements.reason.value,expected:p.updated_at}),view);});paginate(r,view);}
 if(view==='players'){out.innerHTML=`<form data-search><label>Name oder Tag<input name="query" maxlength="40" value="${esc(query)}"></label><button>SUCHEN</button></form>${r.players.map((p,i)=>`<article><strong>${esc(p.username)} · ${esc(p.player_tag)}</strong><p><code>${esc(p.id)}</code></p><p>${esc(p.role)} · ${p.region?'Freiwillige Region: '+esc(p.region.country)+' '+esc(p.region.region||''):'Region nicht angegeben'} · Level ${esc(p.level)} · ${esc(p.rounds_played)} Runden · ${esc(p.wins)} Siege</p><p>Erstellt: ${esc(p.created_at)} · Zuletzt: ${esc(p.last_seen_at||'unbekannt')}</p><p>${p.ban?'Gesperrt: '+esc(p.ban.reason):'Keine aktive Sperre'}</p>${permissions.includes('bans')?`<button data-ban="${i}">${p.ban?'ENTSPERREN':'SPERREN'}</button>`:''}${permissions.includes('roles')?`<button data-role="${i}">ROLLE ÄNDERN</button>`:''}</article>`).join('')}`;out.querySelector('[data-search]').onsubmit=e=>{e.preventDefault();query=e.currentTarget.elements.query.value;page=0;void show(view);};out.querySelectorAll('[data-ban]').forEach(b=>b.onclick=()=>{const p=r.players[+b.dataset.ban];mutation(p.ban?'Sperre aufheben':'Spieler sperren',`<p>${esc(p.username)} · <code>${esc(p.id)}</code></p><label>Dauer<select name="hours">${options({'1':'1 Stunde','24':'24 Stunden','168':'7 Tage','720':'30 Tage','0':'Dauerhaft'})}</select></label>`,f=>api('admin-ban',{targetId:p.id,unban:!!p.ban,hours:+f.elements.hours.value,reason:f.elements.reason.value}),view);});out.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{const p=r.players[+b.dataset.role];mutation('Rolle ändern',`<p>${esc(p.username)} · <code>${esc(p.id)}</code></p><label>Rolle<select name="role">${options({user:'Spieler',moderator:'Moderator',admin:'Administrator',super_admin:'Super Administrator'})}</select></label>`,f=>api('admin-role',{targetId:p.id,role:f.elements.role.value,reason:f.elements.reason.value}),view);});paginate(r,view);}
 if(view==='lobbies'){out.innerHTML=(r.lobbies||[]).map((p,i)=>`<article><strong>${esc(p.name)} · ${esc(p.code)}</strong><p>${esc(p.phase)} · ${esc(p.visibility)} · ${esc(p.radius)} m · ${p.connected}/${p.players} verbunden</p><p>Host: <code>${esc(p.hostId)}</code></p><details><summary>Spieler und Verbindungen</summary><pre>${esc(JSON.stringify(p.participants,null,2))}</pre></details>${p.closed?'Geschlossen':`<button data-close="${i}">LOBBY SCHLIESSEN</button>`}</article>`).join('')||'<p>Keine Lobbys.</p>';out.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{const p=r.lobbies[+b.dataset.close];mutation('Lobby '+p.code+' schließen',`<p>${esc(p.name)} · ${p.players} Spieler. Eine laufende Runde wird ohne Belohnung beendet.</p>`,f=>api('admin-lobby-close',{code:p.code,createdAt:p.createdAt,confirmed:true,reason:f.elements.reason.value}),view);});}
 if(view==='stats'){const labels={registered:'Registrierte Konten',active_day:'Aktive heute',active_week:'Aktive letzte 7 Tage',active_month:'Aktive letzte 30 Tage',matches_total:'Erfasste Runden',matches_today:'Runden heute',active_matches:'Laufende Runden',public_lobbies:'Öffentliche Lobbys',private_lobbies:'Private Lobbys',live_players:'Aktuell verbundene Spieler',average_players:'Ø Spieler je Runde',average_seconds:'Ø Spieldauer (Sekunden)',reports_open:'Offene Meldungen'};out.innerHTML=`<p>Runden und Aktivität werden ab dieser Beta-Version erfasst. Frühere Runden werden nicht nachträglich geschätzt.</p><dl>${Object.entries(labels).map(([k,label])=>`<div><dt>${esc(label)}</dt><dd>${esc(r[k]??'Noch keine Daten')}</dd></div>`).join('')}</dl><h3>Betrieb · letzte 24 Stunden</h3><pre>${esc(JSON.stringify(r.operations||[],null,2))}</pre><h3>Freiwillige Region</h3><p>Keine Ableitung aus GPS. Nur Gruppen ab drei Konten.</p><pre>${esc(JSON.stringify(r.regions||[],null,2))}</pre>`;}
 if(view==='audit')out.innerHTML=(r.actions||[]).map(p=>`<article><strong>${esc(p.action)} · ${esc(p.created_at)}</strong><p>${esc(p.reason)}</p><p>Akteur: <code>${esc(p.actor_id||'gelöscht')}</code><br>Ziel: <code>${esc(p.target_id||'gelöscht')}</code></p><pre>${esc(JSON.stringify(p.context))}</pre></article>`).join('')||'<p>Keine Einträge.</p>';
 }catch(error){if(valid()&&attempt===generation){out.textContent='Ansicht konnte nicht geladen werden.';d.querySelector('[role=alert]').textContent=error.message;}}}
 function paginate(r,view){const bar=document.createElement('div');bar.className='adminTabs';bar.innerHTML=`<button data-prev ${page?'':'disabled'}>ZURÜCK</button><span>Seite ${page+1}</span><button data-next ${r.hasMore?'':'disabled'}>WEITER</button>`;bar.querySelector('[data-prev]').onclick=()=>{page=Math.max(0,page-1);void show(view);};bar.querySelector('[data-next]').onclick=()=>{page++;void show(view);};out.append(bar);}
 d.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{page=0;void show(b.dataset.view);});d.showModal();await show('reports');
 }
 const reported=new Map();
 function logError(category='FRONTEND'){try{if(!authSession?.user?.id)return;const now=Date.now();if((reported.get(category)||0)>now)return;reported.set(category,now+10000);void api('client-error',{category}).catch(()=>{});}catch{}}
 window.addEventListener('error',()=>logError());window.addEventListener('unhandledrejection',()=>logError());
 window.betaUI={openAdmin,onboard,report,logError};
})();
