'use strict';
/* Persistent social extension. Existing friends/chat, gameplay and XP paths stay intact. */
(function(){
 const $=id=>document.getElementById(id),e=v=>esc(String(v??'')),n=v=>Math.max(0,Number(v)||0).toLocaleString('de-DE'),icon=name=>appIcon(name);
 const roles={CHIEF:'Crew-Chef',VICE:'Vize-Chef',OFFICER:'Officer',MEMBER:'Mitglied'},power={CHIEF:4,VICE:3,OFFICER:2,MEMBER:1};
 const modes={OPEN:'Öffentlich',REQUEST:'Auf Anfrage',INVITE:'Nur Einladung'};
 let data=null,progress=null,lastProgress=0,lastCrew=0,crewLoading=false,account='',generation=0,busy=false,refreshTimer,rankingScope='global',rankingPage=0,rankingRows=[],searchPage=0,searchQuery='';
 const read=(section,query='',page=0)=>socialRpc('chs_community_read',{section,query,page});
 const button=(label,action,attrs='',style='')=>'<button type="button" class="hubButton '+style+'" data-hub="'+action+'" '+attrs+'>'+label+'</button>';
 const avatar=p=>'<span class="hubAvatar frame-'+e(['copper','neon','chrome','champion'].includes(p.frame)?p.frame:'default')+'">'+socialAvatarMarkup(p)+'</span>';
 function reset(){generation++;clearTimeout(refreshTimer);account='';data=progress=null;lastProgress=lastCrew=0;crewLoading=false;busy=false;rankingRows=[];document.querySelectorAll('[data-hub-dialog]').forEach(d=>d.remove());if($('crewContent'))$('crewContent').replaceChildren();document.documentElement.style.removeProperty('--personal-scene');}
 function session(){const id=authSession?.user?.id;if(!id)return null;if(account!==id){reset();account=id;}return {id,epoch:generation};}
 const current=s=>s&&authSession?.user?.id===s.id&&generation===s.epoch;
 function sheet(id,title,html){let d=$(id);if(!d){d=document.createElement('dialog');d.id=id;d.className='hubSheet';d.dataset.hubDialog='';document.body.append(d);}d.innerHTML='<header><div><span class="hubEyebrow">CAR HIDE & SEEK</span><h2>'+e(title)+'</h2></div>'+button('×','close','aria-label="Schließen"','hubClose')+'</header><div class="hubSheetBody">'+html+'</div>';if(!d.open)d.showModal();return d;}
 function message(error){toast(error?.message||'Aktion fehlgeschlagen.');}
 async function mutate(action,payload={}){const s=session();if(!s||busy)return false;busy=true;document.querySelectorAll('[data-hub-dialog] button,#crewContent button').forEach(b=>b.disabled=true);try{await socialRpc('chs_crew_action',{action,payload});if(!current(s))return false;await refreshCrew();lastProgress=0;await refreshProgress();toast('Gespeichert.');return true;}catch(err){if(current(s))message(err);return false;}finally{if(current(s)){busy=false;document.querySelectorAll('[data-hub-dialog] button,#crewContent button').forEach(b=>b.disabled=false);}}}
 function progressInfo(p=progress||dbProfile){const level=Math.max(1,Math.min(50,Number(p?.level)||1)),xp=Math.max(0,Number(p?.xp)||0),start=(level-1)*1000,end=level*1000,max=level===50;return {level,xp,start,end,max,within:Math.min(1000,Math.max(0,xp-start)),remaining:Math.max(0,end-xp)};}
 function rewardPreview(reward){return reward.kind==='frame'?avatar({username:dbProfile?.username||'Du',avatar_url:dbProfile?.avatar_url,frame:reward.value}):'<span class="hubTitlePreview">'+e(reward.label)+'</span>';}
 function nextRewardMarkup(p=progress){if(!p?.rewards)return '';const info=progressInfo(p),next=p.rewards.find(r=>r.level>info.level);return next?'<div class="hubRewardPreview">'+rewardPreview(next)+'<div><strong>'+e(next.label)+'</strong><small>Freischaltung ab Level '+next.level+'</small><small>Noch '+n(Math.max(0,(next.level-1)*1000-info.xp))+' XP · rein kosmetisch</small></div></div>':'<p>Alle Level-Belohnungen freigeschaltet.</p>';}
 function renderRoundProgress(){const node=$('roundRewardProgress');if(!node)return;const info=progressInfo();node.innerHTML='<p>Gespeicherter Fortschritt · Level '+info.level+' · '+n(info.xp)+' Gesamt-XP</p><progress max="1000" value="'+(info.max?1000:info.within)+'"></progress>'+nextRewardMarkup();}
 function miniProgress(){window.roundExperience?.ensureHelp?.();if(!dbProfile)return;const p=progressInfo(),next=progress?.rewards?.find(r=>r.level>p.level);let line=$('profileLevelDetails');if(!line){line=document.createElement('div');line.id='profileLevelDetails';document.querySelector('#profile .profileProgress')?.append(line);}if(line)line.innerHTML='<span>'+(p.max?'Höchstes Level erreicht':n(p.remaining)+' XP bis Level '+(p.level+1))+'</span>'+button('Level & Belohnungen '+icon('arrow'),'progress','aria-label="Leveldetails öffnen"');
  if($('profileProgressBar'))$('profileProgressBar').style.width=(p.max?100:p.within/10)+'%';const xp=$('profileXpText');if(xp)xp.textContent=p.max?n(p.xp)+' Gesamt-XP':n(p.within)+' / 1.000 XP';
  const summary=$('homeSeasonSummary');if(summary){const b=summary.querySelector('button');if(b){b.removeAttribute('data-page');b.dataset.hub='progress';b.setAttribute('aria-label','Leveldetails öffnen');}let hint=summary.querySelector('[data-next-reward]');if(!hint){hint=document.createElement('small');hint.dataset.nextReward='';summary.querySelector('div')?.append(hint);}hint.textContent=(p.max?'Maximales Level':n(p.remaining)+' XP bis Level '+(p.level+1))+(next?' · Nächste Belohnung: '+next.label:'');}
  document.querySelectorAll('#profileAvatar,#homeGreetingAvatar').forEach(el=>{el.dataset.hubFrame=progress?.frame||'default';});
 }
 async function refreshProgress(){const s=session();if(!s||Date.now()-lastProgress<15000){miniProgress();return;}lastProgress=Date.now();try{const p=await read('progress');if(!current(s))return;progress=p;miniProgress();renderRoundProgress();}catch(err){if(current(s)){lastProgress=0;if($('progressSheet')?.open)$('progressSheet').querySelector('.hubSheetBody').textContent=err.message;}}}
 function setScene(){const bg=lobbyScene.backgrounds.find(x=>x.id===getLobbyBackground());if(bg)document.documentElement.style.setProperty('--personal-scene','url("'+bg.image+'")');}
 async function openProgress(){const s=session();if(!s)return;sheet('progressSheet','Dein Fortschritt','<p role="status">Fortschritt wird geladen …</p>');try{const [p,globalRank,crewRank]=await Promise.all([read('progress'),read('global'),read('crew_ranking')]);if(!current(s)||!$('progressSheet')?.open)return;progress=p;lastProgress=Date.now();miniProgress();const info=progressInfo(p),stats=p.stats||{},next=p.rewards.find(r=>r.level>info.level);const statIcons={'Spiele':'flag','Siege':'trophy','Gefundene Spieler':'target','Sucher-Siege':'search','Verstecker-Siege':'shield','Siegquote':'chart','Gesamt-XP / Punkte':'bolt','Global':'globe','Crew':'people'};const row=(label,value)=>'<div class="hubStatCard '+(label==='Siege'?'hubStatWins':label==='Gesamt-XP / Punkte'?'hubStatXP':'')+'"><span class="hubStatIcon">'+icon(statIcons[label]||'chart')+'</span><strong>'+e(value)+'</strong><span class="hubStatLabel">'+e(label)+'</span></div>';
  const levels=Array.from({length:50},(_,i)=>{const level=i+1,rewards=p.rewards.filter(r=>r.level===level);return '<li class="'+(level===info.level?'currentLevel':'')+'"><strong>Level '+level+'</strong><span>'+n((level-1)*1000)+' Gesamt-XP</span>'+rewards.map(r=>'<div class="hubReward">'+rewardPreview(r)+'<span>'+e(r.label)+(level>info.level?'<small>Level '+level+' erforderlich</small>':'<small>'+(p[r.kind]===r.value?'Angelegt':'Freigeschaltet')+'</small>')+'</span>'+(level<=info.level?button((p[r.kind]===r.value?'Ausgewählt':'Anlegen'),'equip','data-reward="'+e(r.id)+'"'):'')+'</div>').join('')+'</li>';}).join('');
  sheet('progressSheet','Dein Fortschritt','<div class="hubProgressHero"><span>LEVEL</span><strong>'+info.level+'</strong><p>'+(info.max?n(info.xp)+' Gesamt-XP':n(info.within)+' / 1.000 XP')+'</p><progress max="1000" value="'+(info.max?1000:info.within)+'"></progress><p>'+(info.max?'Höchstes Level erreicht':n(info.remaining)+' XP bis Level '+(info.level+1))+'</p><small>'+(next?'Nächste Freischaltung · '+e(next.label)+' · Level '+next.level:'Alle Level-Belohnungen freigeschaltet')+'</small></div>'+nextRewardMarkup(p)+'<div class="hubPerformanceHeading"><span>'+icon('chart')+'</span><div><small>PLAYER STATS</small><h3>Deine Statistik</h3></div></div><div class="hubStats hubPerformanceStats">'+row('Spiele',n(stats.games))+row('Siege',n(stats.wins))+row('Gefundene Spieler',n(stats.finds))+row('Sucher-Siege',n(stats.seeker_wins))+row('Verstecker-Siege',n(stats.hider_wins))+row('Siegquote',stats.games?Math.round(stats.wins/stats.games*100)+'%':'0%')+row('Gesamt-XP / Punkte',n(info.xp))+row('Global',globalRank.self?'#'+globalRank.self.position:'–')+row('Crew',crewRank.self?'#'+crewRank.self.position:'Keine Crew')+'</div><p class="hubHint">1 Gesamt-XP = 1 Ranglistenpunkt. Bei gleichen XP entscheiden Siege und anschließend die stabile Spieler-ID. Rollen-Siege zählen gespeicherte Rundenergebnisse.</p>'+button(icon('trophy')+' Ranglisten öffnen','ranking')+'<h3>Level & Belohnungen</h3><p class="hubHint">Rein kosmetisch. Kein Vorteil im Spiel.</p><div class="hubInline">'+button('Standardrahmen','equip','data-reward="reset_frame"')+button('Titel entfernen','equip','data-reward="reset_title"')+'</div><ol class="hubLevels">'+levels+'</ol>');
 }catch(err){if(current(s))sheet('progressSheet','Dein Fortschritt','<p>'+e(err.message)+'</p>'+button('Erneut laden','progress'));}}
 function rankRow(p){return '<article class="hubRankRow '+(p.user_id===authSession?.user?.id?'isMe':'')+'"><b>'+p.position+'</b>'+avatar(p)+'<div><strong>'+e(p.username)+(p.user_id===authSession?.user?.id?' · Du':'')+'</strong><small>Level '+p.level+(p.title?' · '+e(p.title):'')+'</small></div><span>'+n(p.points)+'<small>Punkte</small></span></article>';}
 async function showRanking(scope='global',more=false){const s=session();if(!s)return;rankingScope=scope;if(!more){rankingPage=0;rankingRows=[];sheet('rankingSheet','Ranglisten','<p role="status">Rangliste wird geladen …</p>');}const requestedPage=rankingPage;try{const result=await read(scope,'',requestedPage);if(!current(s)||rankingScope!==scope||!$('rankingSheet')?.open)return;rankingRows=more?[...rankingRows,...result.rows]:result.rows;
  const podium=rankingRows.slice(0,3).map(p=>'<article class="hubPodiumStep podium'+p.position+' '+(p.user_id===s.id?'isMe':'')+'">'+avatar(p)+'<strong>'+e(p.username)+'</strong><small>Level '+p.level+'</small><span>'+n(p.points)+' XP</span><div>'+icon('trophy')+'<b>'+p.position+'</b></div></article>').join('');
  sheet('rankingSheet','Ranglisten','<div class="hubTabs">'+button('GLOBAL','ranking','data-scope="global" aria-pressed="'+(scope==='global')+'"')+button('CREW','ranking','data-scope="crew_ranking" aria-pressed="'+(scope==='crew_ranking')+'"')+'</div><p class="hubHint">Gesamt-XP · '+n(result.total)+' Spieler</p>'+(rankingRows.length?'<div class="hubPodium">'+podium+'</div><div class="hubRankList">'+rankingRows.slice(3).map(rankRow).join('')+'</div>':'<div class="hubEmpty">'+icon('people')+'<h3>'+(scope==='crew_ranking'?'Deine Crew wartet auf dich':'Noch keine Platzierungen')+'</h3><p>'+(scope==='crew_ranking'?'Tritt einer Crew bei oder gründe deine eigene.':'Spiele eine Runde und sammle XP.')+'</p></div>')+(result.self?'<aside class="hubOwnRank"><small>DEINE PLATZIERUNG</small>'+rankRow(result.self)+'</aside>':'')+(rankingRows.length<result.total?button('Weitere 50 laden','ranking-more'):'')+'<p class="hubHint">1 XP = 1 Punkt. Deine Platzierung bleibt auch außerhalb der ersten 50 sichtbar.</p>');
 }catch(err){if(current(s))sheet('rankingSheet','Ranglisten','<p>'+e(err.message)+'</p>'+button('Erneut laden','ranking','data-scope="'+e(scope)+'"'));}}
 async function refreshCrew(){const s=session();if(!s||crewLoading)return;crewLoading=true;try{const value=await read('crew');if(!current(s))return;data=value;lastCrew=Date.now();renderCrew();if(data.crew)renderHomeCrew();else window.referenceUI?.renderCrew();}catch(err){if(current(s)&&$('crewContent'))$('crewContent').innerHTML='<p>'+e(err.message)+'</p>'+button('Erneut laden','refresh');}finally{if(current(s))crewLoading=false;}}
 function renderHomeCrew(){const box=$('homeCrewPeople');if(!box||!data?.crew)return;const markup=data.members.slice(0,8).map(p=>'<button type="button" class="referenceCrewPerson" data-hub="crew"><span class="referenceCrewPortrait">'+avatar(p)+(p.online?'<i class="referenceOnline" aria-label="Online"></i>':'')+'</span><strong>'+e(p.username)+'</strong><small>'+(p.online?'Online':'Offline')+'</small></button>').join('');box.innerHTML=markup;box.dataset.markup=markup;}
 function memberRow(p){const chief=data.crew.my_role==='CHIEF',vice=data.crew.my_role==='VICE',canEdit=p.user_id!==account&&((chief&&p.role!=='CHIEF')||(vice&&power[p.role]<3));return '<article class="hubMember">'+avatar(p)+'<div><strong>'+e(p.username)+(p.user_id===account?' · Du':'')+'</strong><small>'+e(roles[p.role])+' · Level '+p.level+'</small><small><i class="'+(p.online?'hubOnline':'hubOffline')+'"></i> '+(p.online?'Online':'Offline')+(p.title?' · '+e(p.title):'')+'</small></div><span>'+n(p.points)+'<small>XP</small></span>'+(canEdit?button('•••','member','data-user="'+p.user_id+'" aria-label="'+e(p.username)+' verwalten"'):'')+'</article>';}
 function renderCrew(){const box=$('crewContent');if(!box||!data)return;const c=data.crew;
  const invites=data.invitations.map(c=>'<article class="hubCard"><small>EINLADUNG VON '+e(c.invited_by||'DEINER CREW')+'</small><h3>'+e(c.name)+' <span>['+e(c.tag)+']</span></h3><p>'+e(c.description)+'</p><div class="hubInline">'+button('Annehmen','accept_invite','data-crew="'+c.id+'"','primary')+button('Ablehnen','decline_invite','data-crew="'+c.id+'"')+'</div></article>').join('');
  if(!c){box.innerHTML=invites+'<div class="hubCrewWelcome">'+icon('shield')+'<span class="hubEyebrow">GEMEINSAM AUF DIE STRASSE</span><h2>Finde deine Crew.</h2><p>Ein gemeinsamer Name, echte Rollen und eure eigene Rangliste.</p>'+button(icon('plus')+' Crew erstellen','create-form','','primary')+button(icon('search')+' Crew suchen','search')+'</div>';return;}
  const leaders=[...data.members].sort((a,b)=>b.points-a.points).slice(0,3);
  box.innerHTML='<header class="hubCrewHero"><div class="hubCrewLogo">'+icon(c.logo)+'</div><span class="hubEyebrow">['+e(c.tag)+'] · '+e(modes[c.join_mode])+'</span><h2>'+e(c.name)+'</h2><p>'+data.members.length+' / 50 Mitglieder · '+n(c.points)+' XP</p><span class="hubRolePill">'+e(roles[c.my_role])+'</span></header><div class="hubTabs">'+button(icon('trophy')+' Ranking','ranking','data-scope="crew_ranking"')+button(icon('people')+' Einladen','invite-form')+button(icon('gear')+' Info','crew-info')+'</div><div class="hubCard"><h3>Die Spitze deiner Crew</h3><div class="hubTopCrew">'+leaders.map((p,i)=>'<div>'+avatar(p)+'<strong>'+(i+1)+'. '+e(p.username)+'</strong><small>'+n(p.points)+' XP</small></div>').join('')+'</div></div><div class="hubSectionHeading"><h3>Mitglieder</h3><span>'+data.members.length+'</span></div><div class="hubMemberList">'+data.members.map(memberRow).join('')+'</div>'+(data.requests.length?'<h3>Beitrittsanfragen</h3>'+data.requests.map(p=>'<article class="hubRequest">'+avatar(p)+'<strong>'+e(p.username)+'</strong>'+button('Annehmen','review_request','data-user="'+p.user_id+'" data-accept="true"')+button('Ablehnen','review_request','data-user="'+p.user_id+'" data-accept="false"')+'</article>').join(''):'')+(data.sent_invites.length?'<h3>Offene Einladungen</h3>'+data.sent_invites.map(p=>'<article class="hubRequest">'+avatar(p)+'<strong>'+e(p.username)+'</strong>'+button('Zurückziehen','revoke_invite','data-user="'+p.user_id+'"')+'</article>').join(''):'');
 }
 function crewForm(edit=false){const c=edit?data?.crew:null,chief=!edit||c.my_role==='CHIEF';const d=sheet('crewFormSheet',edit?'Crew bearbeiten':'Crew erstellen','<form id="hubCrewForm">'+(chief?'<label>Name<input name="name" minlength="3" maxlength="32" required></label><label>Kürzel<input name="tag" minlength="2" maxlength="6" pattern="[A-Za-z0-9]{2,6}" required placeholder="2–6 Buchstaben/Zahlen"></label><label>Logo<select name="logo">'+['shield','crown','target','car','star','bolt'].map((v,i)=>'<option value="'+v+'">'+['Schild','Krone','Ziel','Auto','Stern','Blitz'][i]+'</option>').join('')+'</select></label>':'')+'<label>Beschreibung<textarea name="description" maxlength="280" rows="3"></textarea></label><label>Beitrittsart<select name="join_mode">'+Object.entries(modes).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join('')+'</select></label>'+(chief?'<label class="hubCheck"><input type="checkbox" name="member_invites"> Mitglieder dürfen Freunde einladen</label>':'')+'<p class="hubHint">Eine Crew pro Spieler · maximal 50 Mitglieder.</p><button class="hubButton primary" type="submit">'+(edit?'Speichern':'Crew erstellen')+'</button></form>');const form=d.querySelector('form');if(c)for(const el of form.elements){if(el.name in c){if(el.type==='checkbox')el.checked=c[el.name];else el.value=c[el.name];}}form.onsubmit=async event=>{event.preventDefault();const payload=Object.fromEntries(new FormData(form));if(chief)payload.member_invites=form.elements.member_invites.checked;if(await mutate(edit?'update':'create',payload))d.close();};}
 async function searchCrews(more=false){const s=session();if(!s)return;if(!more){searchPage=0;sheet('crewSearchSheet','Crew suchen','<form id="hubCrewSearch"><label>Name oder Kürzel<input name="q" maxlength="32" placeholder="Deine Crew finden"></label><button class="hubButton" type="submit">Suchen</button></form><div id="hubCrewSearchResults" role="status">Crews werden geladen …</div>');$('hubCrewSearch').elements.q.value=searchQuery;$('hubCrewSearch').onsubmit=event=>{event.preventDefault();searchQuery=$('hubCrewSearch').elements.q.value;void searchCrews();};}try{const rows=await read('search',searchQuery,searchPage);if(!current(s)||!$('crewSearchSheet')?.open)return;const box=$('hubCrewSearchResults');box.querySelector('[data-hub="search-more"]')?.remove();const html=rows.map(c=>'<article class="hubSearchCrew"><span class="hubCrewLogo">'+icon(c.logo)+'</span><div><h3>'+e(c.name)+'</h3><small>['+e(c.tag)+'] · '+c.members+'/50 · '+n(c.points)+' XP</small><p>'+e(c.description)+'</p><small>'+e(modes[c.join_mode])+'</small></div>'+(data?.crew?'':c.requested?button('Anfrage zurückziehen','cancel_request','data-crew="'+c.id+'"'):c.members>=50?'<span>Voll</span>':c.join_mode==='INVITE'?'<span class="hubHint">Einladung erforderlich</span>':button(c.join_mode==='OPEN'?'Beitreten':'Anfragen',c.join_mode==='OPEN'?'join':'request','data-crew="'+c.id+'"'))+'</article>').join('');if(more)box.insertAdjacentHTML('beforeend',html);else box.innerHTML=html||'<p>Keine passende Crew gefunden.</p>';if(rows.length===30)box.insertAdjacentHTML('beforeend',button('Weitere Crews','search-more'));}catch(err){if(current(s))$('hubCrewSearchResults').textContent=err.message;}}
 async function inviteForm(){if(!data?.crew)return;if(data.crew.my_role==='MEMBER'&&!data.crew.member_invites){sheet('crewInviteSheet','Freunde einladen','<p>Dein Crew-Chef hat Einladungen für Mitglieder noch nicht freigegeben.</p>');return;}const s=session();sheet('crewInviteSheet','Freunde einladen','<p role="status">Freunde werden geladen …</p>');await loadFriends();if(!current(s)||!$('crewInviteSheet')?.open)return;const members=new Set(data.members.map(p=>p.user_id)),rows=socialRows.filter(p=>p.status==='accepted'&&!members.has(p.peer_id));sheet('crewInviteSheet','Freunde einladen',rows.length?rows.map(p=>'<article class="hubRequest">'+avatar(p)+'<strong>'+e(friendDisplayName(p))+'</strong>'+button('Einladen','invite','data-user="'+p.peer_id+'"')+'</article>').join(''):'<p>Verbinde dich zuerst über Freunde mit deinen Mitspielern.</p>'+button('Freunde öffnen','friends'));}
 function memberSheet(uid){const p=data?.members.find(p=>p.user_id===uid);if(!p)return;const c=data.crew,options=(c.my_role==='CHIEF'?['MEMBER','OFFICER','VICE']:['MEMBER','OFFICER']).map(r=>button(roles[r],'role','data-user="'+uid+'" data-role="'+r+'" aria-pressed="'+(r===p.role)+'"')).join('');sheet('memberSheet',p.username,'<div class="hubMemberSummary">'+avatar(p)+'<p>'+e(roles[p.role])+' · '+n(p.points)+' XP</p></div><h3>Rolle zuweisen</h3><div class="hubInline">'+options+'</div>'+(c.my_role==='CHIEF'?button('Crew-Leitung übertragen','confirm-transfer','data-user="'+uid+'"'):'')+button('Aus Crew entfernen','confirm-kick','data-user="'+uid+'"','danger'));}
 function infoSheet(){const c=data?.crew;if(!c)return;sheet('crewInfoSheet','Crew-Info','<div class="hubCrewHero"><div class="hubCrewLogo">'+icon(c.logo)+'</div><h3>'+e(c.name)+' ['+e(c.tag)+']</h3><p>'+e(c.description||'Noch keine Beschreibung.')+'</p></div><div class="hubStats"><div><strong>'+data.members.length+'</strong><span>Mitglieder</span></div><div><strong>'+n(c.points)+'</strong><span>Gesamt-XP</span></div></div><p>'+e(modes[c.join_mode])+' · gegründet am '+e(new Date(c.created_at).toLocaleDateString('de-DE'))+'</p><p class="hubHint">Chef: alle Rechte. Vize: Beschreibung, Beitrittsart und untergeordnete Mitglieder verwalten. Officer: Einladungen und Anfragen. Mitglieder: Crew nutzen; Einladungen nach Freigabe.</p>'+(power[c.my_role]>=3?button('Crew bearbeiten','edit-form'):'')+button('Crew verlassen','confirm-leave','','danger')+(c.my_role==='CHIEF'?button('Crew löschen','confirm-delete','','danger'):''));}
 function confirmAction(action,uid){const c=data?.crew;if(!c)return;const titles={leave:'Crew verlassen?',delete:'Crew endgültig löschen?',transfer:'Crew-Leitung übertragen?',kick:'Mitglied entfernen?'};const d=sheet('crewConfirmSheet',titles[action],'<p>'+(action==='leave'&&c.my_role==='CHIEF'?'Die Leitung geht automatisch an die höchste verbleibende Rolle. Eine leere Crew wird gelöscht.':action==='delete'?'Alle Crew-Mitgliedschaften und offenen Crew-Einladungen werden entfernt. Profile, Fahrzeuge, Freunde und XP bleiben erhalten.':'Diese Änderung betrifft die Crew-Mitgliedschaft.')+'</p>'+(action==='delete'?'<label>Kürzel '+e(c.tag)+' eingeben<input id="confirmCrewTag" autocomplete="off"></label>':'')+button('Bestätigen','confirmed','data-action="'+action+'" '+(uid?'data-user="'+uid+'"':''),'danger')+button('Abbrechen','close'));}
 function openBackground(lobby=false){if(!authSession)return;const host=lobby&&state?.lobby?.state==='LOBBY'&&state.lobby.hostId===gameSession?.userId;if(lobby&&!host){toast('Nur der Host kann den Lobby-Hintergrund ändern.');return;}let selected=lobby?state.lobby.background:getLobbyBackground();const options=lobbyScene.backgrounds;const d=sheet('backgroundSheet',lobby?'Lobby-Hintergrund':'Dein Hintergrund','<div class="hubBackgroundPreview" id="hubBackgroundPreview"></div><div class="hubBackgroundGrid">'+options.map(b=>'<button type="button" data-scene-choice="'+b.id+'" aria-pressed="'+(b.id===selected)+'"><img src="'+e(b.image)+'" alt="" loading="lazy"><strong>'+e(b.name)+'</strong><small data-selection>'+ (b.id===selected?'Ausgewählt':'Vorschau')+'</small></button>').join('')+'</div><p class="hubHint">'+(lobby?'Die gespeicherte Auswahl gilt für alle Spieler dieser Lobby.':'Deine Auswahl wird im Konto gespeichert und für neue Lobbys verwendet.')+'</p>'+button('Hintergrund speichern','save-scene','','primary'));const preview=()=>{$('hubBackgroundPreview').style.backgroundImage='url("'+options.find(b=>b.id===selected).image+'")';};preview();d.querySelectorAll('[data-scene-choice]').forEach(b=>b.onclick=()=>{selected=b.dataset.sceneChoice;d.querySelectorAll('[data-scene-choice]').forEach(x=>{x.setAttribute('aria-pressed',String(x===b));x.querySelector('[data-selection]').textContent=x===b?'Ausgewählt':'Vorschau';});preview();});d.querySelector('[data-hub="save-scene"]').onclick=async event=>{const s=session(),b=event.currentTarget;b.disabled=true;try{if(lobby){const credentials=gameCredentials();await api('background',{...credentials,background:selected});if(!current(s)||gameSession?.code!==credentials.code)return;await poll();}else{const {data:update,error}=await supabaseClient.auth.updateUser({data:{lobby_background:selected}});if(error)throw error;if(!current(s))return;if(update?.user)authSession.user=update.user;localStorage.setItem(lobbyBackgroundKey(),selected);setScene();}d.close();toast('Hintergrund gespeichert.');}catch(err){message(err);}finally{b.disabled=false;}};}
 async function click(event){const b=event.target.closest('[data-hub]');if(!b||b.disabled)return;const action=b.dataset.hub;try{
  if(action==='close'){b.closest('dialog').close();return;}if(action==='progress'){await openProgress();return;}if(action==='ranking'){await showRanking(b.dataset.scope||'global');return;}if(action==='ranking-more'){b.disabled=true;rankingPage++;await showRanking(rankingScope,true);return;}
  if(action==='friends'){b.closest('dialog')?.close();openPage('friends');return;}if(action==='crew'){openPage('crew');return;}if(action==='refresh'){await refreshCrew();return;}
  if(action==='create-form'||action==='edit-form'){crewForm(action==='edit-form');return;}if(action==='search'){await searchCrews();return;}if(action==='search-more'){b.disabled=true;searchPage++;await searchCrews(true);return;}if(action==='invite-form'){await inviteForm();return;}if(action==='crew-info'){infoSheet();return;}if(action==='member'){memberSheet(b.dataset.user);return;}
  if(action.startsWith('confirm-')){confirmAction(action.slice(8),b.dataset.user);return;}if(action==='confirmed'){const ok=await mutate(b.dataset.action,{user_id:b.dataset.user,confirm_tag:$('confirmCrewTag')?.value});if(ok)document.querySelectorAll('#crewConfirmSheet,#crewInfoSheet,#memberSheet').forEach(d=>d.close());return;}
  if(action==='background'){openBackground(false);return;}if(action==='lobby-background'){openBackground(true);return;}if(action==='save-scene')return;
  const payload={};if(b.dataset.crew)payload.crew_id=b.dataset.crew;if(b.dataset.user)payload.user_id=b.dataset.user;if(b.dataset.role)payload.role=b.dataset.role;if(b.dataset.accept)payload.accept=b.dataset.accept==='true';if(b.dataset.reward)payload.reward=b.dataset.reward;
  if(await mutate(action,payload)){if(action==='equip')await openProgress();else if(['join','accept_invite'].includes(action)){b.closest('dialog')?.close();openPage('crew');}else if(['request','cancel_request'].includes(action))await searchCrews();else if(action==='role')$('memberSheet')?.close();else if(action==='invite'){b.textContent='Eingeladen';b.disabled=true;}}
 }catch(err){message(err);}}
 function onPage(page){clearTimeout(refreshTimer);if(!authSession)return;if(page==='friends')document.querySelector('#bottomNav [data-page="crew"]')?.classList.add('active');if(page==='crew'){if(!data)$('crewContent').innerHTML='<p role="status">Deine Crew wird geladen …</p>';void refreshCrew();refreshTimer=setTimeout(()=>{if($('crew')?.classList.contains('active')&&!document.hidden)onPage('crew');},15000);}if(page==='home'||page==='profile'){setScene();void refreshProgress();if(Date.now()-lastCrew>15000)void refreshCrew();}}
 function setup(){const main=$('app'),page=document.createElement('section');page.id='crew';page.className='page';page.innerHTML='<div class="hubPageHeading"><div><span class="hubEyebrow">DEINE COMMUNITY</span><h1>CREW</h1></div>'+button(icon('trophy'),'ranking','aria-label="Ranglisten öffnen"')+'</div><div class="hubTabs">'+button(icon('shield')+' Meine Crew','crew','aria-pressed="true"')+button(icon('chat')+' Freunde & Chats','friends')+'</div>'+button(icon('search')+' Crew suchen','search')+'<div id="crewContent"></div>';main.append(page);
  document.querySelectorAll('#bottomNav [data-page="friends"]').forEach(b=>b.dataset.page='crew');
  const friendBack=document.createElement('button');friendBack.type='button';friendBack.className='hubButton';friendBack.dataset.hub='crew';friendBack.innerHTML=icon('shield')+' Meine Crew';$('friends')?.prepend(friendBack);
  for(const selector of ['#profile .profileProgress','#home .referenceCrew']){const parent=document.querySelector(selector);if(parent){const b=document.createElement('button');b.type='button';b.dataset.hub='background';b.className='hubSceneButton';b.innerHTML=icon('sparkles')+' Hintergrund wählen';parent.append(b);}}
  const oldBackground=$('lobbyBackgroundControls');if(oldBackground){oldBackground.classList.add('hubOldScenes');oldBackground.insertAdjacentHTML('afterend',button(icon('sparkles')+' Hintergründe ansehen','lobby-background'));}
  const quick=$('openPlay');if(quick?.querySelector('.actionSymbol'))quick.querySelector('.actionSymbol').innerHTML=icon('people');
  $('homeCreateLobby')?.querySelector('.actionSymbol')?.replaceChildren();if($('homeCreateLobby')?.querySelector('.actionSymbol'))$('homeCreateLobby').querySelector('.actionSymbol').innerHTML=icon('plus');
  document.querySelectorAll('#home .referenceSectionHeading button,#profile .referenceSectionHeading button').forEach(b=>{b.removeAttribute('data-page');b.dataset.hub='crew';});
  document.addEventListener('click',click);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&$('crew')?.classList.contains('active'))onPage('crew');});
  miniProgress();if(authSession){setScene();void refreshProgress();}
 }
 window.crewUI={openProgress,renderRoundProgress,async refreshProgress(){lastProgress=0;await refreshProgress();},onPage,onProfile(){setScene();miniProgress();void refreshProgress();if(Date.now()-lastCrew>15000)void refreshCrew();},renderHomeCrew,miniProgress,reset};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup,{once:true});else setup();
})();
