'use strict';
const crypto=require('node:crypto');
const VERSION='2026-10-01.1';
function documents(env=process.env){
  // Personal operator details belong in deployment configuration, not in this
  // public repository. Missing values keep the legal release gate closed.
  const operator={name:env.CHS_OPERATOR_NAME||'',address:env.CHS_OPERATOR_ADDRESS||'',email:env.CHS_OPERATOR_EMAIL||''};
  const ready=!!(operator.name.trim()&&operator.address.trim()&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(operator.email)&&env.CHS_LEGAL_REVIEWED==='true');
  const terms=[
    ['Anbieter und Teilnahme',`CAR HIDE & SEEK wird von ${operator.name} angeboten. Teilnahme ab 18 Jahren. Gegenstand ist ein freiwilliges, ortsbezogenes Spiel; die App ist kein Verkehrsleitsystem, keine Sicherheitsausrüstung und kein Notrufdienst. Diese Fassung regelt die kostenlose Spielversion. Kostenpflichtige Leistungen werden erst mit gesonderten transparenten Bedingungen angeboten.`],
    ['Sicherheit hat Vorrang','Keine Rennen, riskanten Fahrmanöver, Verfolgungsfahrten oder Regelverstöße. Straßenverkehrsrecht, Eigentumsrechte und örtliche Verbote gelten immer. Nur sichere, legal zugängliche Orte verwenden. Der Host muss einen geeigneten Treffpunkt wählen; Karten und Spielradien bestätigen weder Zugänglichkeit noch Sicherheit eines Ortes. Nicht während der Fahrt tippen oder suchen. Fahrer bedienen die App ausschließlich nach sicherem Parken; während der Fahrt bedient ein tatsächlicher Beifahrer. Die Auswahl „Beifahrer“ ist keine Erlaubnis für den Fahrer. Ein Spielziel oder Zeitlimit rechtfertigt nie einen Verkehrsverstoß. Wenn eine Spielsituation unsicher ist: Spiel unterbrechen oder verlassen, auch bei Punktverlust.'],
    ['Spiel und Verfügbarkeit','GPS kann ungenau sein, insbesondere in Gebäuden, Parkhäusern oder bei schlechtem Empfang. Netzwerk- und Geräteausfälle können Spielabläufe beeinflussen. Es gibt keinen Anspruch auf durchgehend fehlerfreie Verfügbarkeit oder ein bestimmtes Spielergebnis. Zwingende gesetzliche Rechte bleiben bestehen.'],
    ['Konten, Bilder und fairer Umgang','Keine gefälschten Standorte, Manipulation, Belästigung oder missbräuchlichen Inhalte. Nur Bilder hochladen, an denen du die erforderlichen Rechte besitzt und deren Veröffentlichung zulässig ist; keine fremden Gesichter, Kennzeichen oder privaten Informationen ohne Berechtigung. Profil- und Fahrzeugfotos sind derzeit über öffentliche Bildadressen erreichbar. Uploads sind freiwillig und können entfernt werden. Die erforderliche einfache Nutzungserlaubnis ist auf Speicherung und Darstellung in der App beschränkt; sie endet mit Entfernung vorbehaltlich technischer Auslaufzeiten und rechtlich erforderlicher Aufbewahrung.'],
    ['Moderation und Einspruch',`Konkrete Regelverstöße können nach Prüfung zu zeitweisen oder dauerhaften Kontosperren führen. Umfang und Dauer sollen zum Verstoß passen. Bei akuten Gefahren kann sofort gesperrt werden. Betroffene erhalten einen Grund und können sich zur Überprüfung an ${operator.email||'den noch einzutragenden Betreiberkontakt'} wenden. Adminrechte dienen Support und Moderation und verändern keine normalen Spielregeln oder Sicherheitsanforderungen. Meldungen werden nicht automatisch als Beweis gewertet.`],
    ['Haftung','Der Anbieter haftet unbeschränkt bei Vorsatz und grober Fahrlässigkeit sowie für schuldhafte Verletzungen von Leben, Körper oder Gesundheit. Bei leicht fahrlässiger Verletzung wesentlicher Vertragspflichten ist die Haftung auf den vorhersehbaren, vertragstypischen Schaden begrenzt. Wesentliche Pflichten sind solche, deren Erfüllung die ordnungsgemäße Nutzung erst ermöglicht und auf deren Einhaltung Nutzer regelmäßig vertrauen dürfen. Im Übrigen ist die Haftung für leicht fahrlässig verursachte Schäden ausgeschlossen. Zwingende gesetzliche Haftung, insbesondere nach dem Produkthaftungsgesetz, sowie ausdrücklich übernommene Garantien bleiben unberührt. Diese Regelung gilt auch zugunsten gesetzlicher Vertreter und Erfüllungsgehilfen. Es wird keine Befreiung von jeglicher Haftung vereinbart.'],
    ['Änderungen und Vertragsende','Du kannst die Nutzung jederzeit beenden. Wesentliche Änderungen werden vor ihrer Anwendung angezeigt und erfordern eine neue Zustimmung für die weitere Teilnahme. Bereits entstandene gesetzliche Rechte bleiben erhalten. Es gilt deutsches Recht; zwingender Verbraucherschutz des gewöhnlichen Aufenthaltsstaates bleibt unberührt. Es wird kein ausschließlicher Gerichtsstand für Verbraucher festgelegt.']
  ];
  const privacy=[
    ['Verantwortlicher und Kontakt',`${operator.name}, ${operator.address||'Anschrift noch nicht eingetragen'}, ${operator.email||'Kontakt-E-Mail noch nicht eingetragen'}. Die Angaben müssen vor Freigabe vervollständigt werden.`],
    ['Konto und Kommunikation','Bei Google-Anmeldung werden Konto-ID, E-Mail und vom Anmeldedienst übermittelte Profilangaben verarbeitet. Hinzu kommen Spielername, Fahrzeuge, ausgewählte Charaktergestaltung, Fortschritt, Freundschaften und Nachrichten. Rechtsgrundlage für erforderliche Kontofunktionen ist Art. 6 Abs. 1 lit. b DSGVO. Kontodaten bleiben für die Nutzungsdauer gespeichert. Konto- und Datenlöschung sowie Auskunft können beim Betreiber angefordert werden; gesetzliche Aufbewahrung und berechtigte Rechtsverteidigung werden im Einzelfall geprüft.'],
    ['Standort im Spiel','Standort, Genauigkeit, Geschwindigkeit und gegebenenfalls Höhe werden bei aktiv genutzter Lobby/Spiel und erteilter Gerätefreigabe verarbeitet, um Teilnahme, Spielregeln und Treffpunkt zu ermöglichen (Art. 6 Abs. 1 lit. b DSGVO). Ohne Standort funktioniert das ortsbezogene Spiel nicht; Rechtstexte und Abmeldung bleiben erreichbar. In der Lobby sehen Teilnehmer die Positionen der Crew. Im Spiel werden Positionen auf eigene Person, Team und den vom Sucher gewählten aktiven Zielkontakt begrenzt. Bei Ausscheiden und Rundenende endet die Standortübertragung; aktive Serverdaten werden spätestens nach sechs Stunden gelöscht. Wiederherstellungsspeicher enthält zwischenzeitlich Spielpositionen; abgelaufene Daten werden bei Wiederherstellung verworfen und der nächste erfolgreiche Speichervorgang ersetzt den alten Stand. Technische Backups beim Dienstleister können länger bestehen; Löschfristen sind vor Produktionsfreigabe mit dem Dienstleister zu bestätigen. Die Gerätestandortfreigabe lässt sich jederzeit in den Geräteeinstellungen entziehen; dann kann die Spielteilnahme enden.'],
    ['Freiwillige Fotos und Gestaltung','Fotos und kosmetische Charaktereinstellungen sind freiwillig. Profil- und Fahrzeugbilder werden in öffentlichen Supabase-Bildspeichern abgelegt und sind über ihre URL auch außerhalb einer Lobby abrufbar. Veröffentliche deshalb keine vertraulichen Inhalte. Entfernen und Ersetzen sind möglich. Zwischenspeicher können eine Aktualisierung verzögern. Eine private Freigabe nur an Mitspieler ist in dieser Version nicht zugesichert.'],
    ['Sicherheit, Moderation und Zustimmungsnachweis','Adminzugriffe auf erforderliche Profil- und Moderationsdaten werden beschränkt. Kontosperren, Begründungen und Adminaktionen dienen Missbrauchsschutz (Art. 6 Abs. 1 lit. f DSGVO; Interesse: Schutz der Nutzer und des Dienstes). Adminansichten enthalten keine Standortkoordinaten oder privaten Direktnachrichten. Zustimmung wird mit Konto-ID, Dokumentversion, Dokument-Hash und Serverzeit nachgewiesen (Art. 6 Abs. 1 lit. b und f DSGVO). Es wird hierfür keine zusätzliche IP-Adresse gespeichert. Spieljournale und Meldungen werden regelmäßig nach 30 Tagen gelöscht. Adminaktionsprotokolle werden nach 90 Tagen gelöscht; aktive Sperrentscheidungen bleiben bis Aufhebung oder Kontolöschung gespeichert. Zustimmungsnachweise bleiben während der Nutzung; bei Vertragsende wird die weitere Erforderlichkeit für Rechtsverteidigung geprüft.'],
    ['Dienstleister und Übermittlungen','Supabase verarbeitet Anmeldung, Datenbank und Bildspeicherung; Render betreibt den Spielserver. Google verarbeitet die gewählte Anmeldung. Karten stammen von OpenFreeMap; der Browser verbindet sich für Karten und Bibliotheken mit OpenFreeMap, jsDelivr und gegebenenfalls unpkg. Dabei können IP-Adresse, Abrufzeit und technische Browserdaten anfallen. Für Treffpunktrouten übermittelt der Server Start- und Zielkoordinaten an den konfigurierten OSRM-Routendienst (derzeit router.project-osrm.org). Ist Hintergrundfreistellung aktiviert, wird das ausdrücklich ausgewählte Fahrzeugfoto an remove.bg übermittelt; diese Funktion ist freiwillig. Hostingregionen, Auftragsverarbeitungsverträge, Unterauftragnehmer und gegebenenfalls Drittlandgarantien nach Art. 44 ff. DSGVO müssen vor Produktionsfreigabe dokumentiert und geprüft werden; diese Fassung behauptet keine ausschließlich deutsche Speicherung.'],
    ['Gerätespeicher und optionale Funktionen','Technisch erforderlicher Gerätespeicher hält Sitzung, laufende Lobby und Gerätevoreinstellungen vor. Es sind in dieser Fassung keine Werbe- oder Analyse-Tracker eingebaut. Freiwillige Töne/Vibration sind separat wählbar. Künftige Werbung, Tracking oder kostenpflichtige Funktionen werden nicht durch diese Erklärung pauschal genehmigt; erforderliche freiwillige Einwilligungen müssen separat und widerrufbar eingeholt werden.'],
    ['Deine Rechte','Unter den gesetzlichen Voraussetzungen hast du Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit sowie Widerspruch gegen Verarbeitungen nach Art. 6 Abs. 1 lit. f DSGVO. Soweit eine Verarbeitung auf Einwilligung beruht, kann sie jederzeit mit Wirkung für die Zukunft widerrufen werden. Du kannst dich bei einer Datenschutzaufsichtsbehörde beschweren, insbesondere der Landesbeauftragten für Datenschutz und Informationsfreiheit Nordrhein-Westfalen (ldi.nrw.de). Die Datenschutzhinweise werden zur Kenntnis genommen; ihre Kenntnisnahme ist keine pauschale Einwilligung in sämtliche Datenverarbeitung.']
  ];
  const content={version:VERSION,operator,terms,privacy,safety:terms[1][1]};
  return {...content,ready,hash:crypto.createHash('sha256').update(JSON.stringify(content)).digest('hex')};
}
module.exports={VERSION,documents};
