'use strict';
// Local HTTP capacity probe. Supabase/auth are deterministic fixtures, never live load.
const http=require('node:http'),{performance}=require('node:perf_hooks'),fs=require('node:fs');
const nativeFetch=global.fetch;let reads=0,writes=0;
const id=n=>`${String(n).padStart(8,'0')}-1111-4111-8111-111111111111`;
Object.assign(process.env,{SUPABASE_SECRET_KEY:'sb_secret_local_fixture',CHS_OPERATOR_NAME:'Local QA',CHS_OPERATOR_ADDRESS:'Test address',CHS_OPERATOR_EMAIL:'test@example.com',CHS_LEGAL_REVIEWED:'true'});
global.fetch=async(url,o={})=>{o.method==='POST'?writes++:reads++;const resource=new URL(url).pathname.split('/').pop();let result=[];if(resource==='user')result={id:id(Number(o.headers.Authorization.split(' ').at(-1)))};if(resource==='chs_legal_acceptances')result=[{accepted_at:new Date().toISOString()}];if(resource==='chs_onboarding')result=[{version:'beta-2026-10-01'}];return {ok:true,status:200,json:async()=>result};};
const app=require('../server'),server=http.createServer(app.handler);
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const results=[];
async function request(n,action,data={},method='POST'){const before=performance.now();const r=await nativeFetch(url+'/api/'+action+(method==='GET'?'?'+new URLSearchParams(data):''),{method,headers:{Authorization:'Bearer '+n,'Content-Type':'application/json'},body:method==='POST'?JSON.stringify(data):undefined});const body=await r.json();if(!r.ok)throw Error(action+' '+r.status+' '+body.error);return {body,ms:performance.now()-before};}
try{for(const count of [50,100,500,1000]){app.lobbies.clear();const sessions=[];for(let n=1;n<=count;n+=10){const c=await request(n,'create',{name:'Local '+n,vehicle:'QA',mode:'PASSENGER'});sessions.push({n,code:c.body.lobby.code,userId:c.body.userId});const peers=await Promise.all(Array.from({length:Math.min(9,count-n)},(_,i)=>request(n+i+1,'join',{code:c.body.lobby.code,name:'Local '+(n+i+1),vehicle:'QA',mode:'PASSENGER'}).then(r=>({n:n+i+1,code:c.body.lobby.code,userId:r.body.userId}))));sessions.push(...peers);}
 const samples=[],start=performance.now(),cpuStart=process.cpuUsage(),r0=reads,w0=writes;
 for(let cycle=0;cycle<3;cycle++){for(let start=0;start<sessions.length;start+=50)await Promise.all(sessions.slice(start,start+50).map(async s=>{const data={code:s.code,userId:s.userId};samples.push((await request(s.n,'state',data,'GET')).ms);samples.push((await request(s.n,'location',{...data,lat:52,lng:13,accuracy:5,speed:0,positionTimestamp:Date.now()})).ms);}));}
 const elapsed=performance.now()-start,cpu=process.cpuUsage(cpuStart);samples.sort((a,b)=>a-b);results.push({clients:count,requests:samples.length,elapsed_ms:Math.round(elapsed),p50_ms:Math.round(samples[Math.floor(samples.length*.5)]),p95_ms:Math.round(samples[Math.floor(samples.length*.95)]),cpu_ms:Math.round((cpu.user+cpu.system)/1000),rss_mb:Math.round(process.memoryUsage().rss/1048576),backend_fixture_reads:reads-r0,backend_fixture_writes:writes-w0,gps_requests:count*3,state_snapshot_writes:0,errors:0});console.log(JSON.stringify(results.at(-1)));}
 fs.writeFileSync(process.argv[2]||'/tmp/chs-beta-load.json',JSON.stringify({date:new Date().toISOString(),scope:'Local HTTP; mocked Supabase/auth; no network latency, active rounds, durable checkpoint writer or real GPS devices. Not production capacity proof.',results},null,2)+'\n');}finally{app.lobbies.clear();await new Promise(r=>server.close(r));global.fetch=nativeFetch;}})().catch(e=>{console.error(e.message);process.exitCode=1;});
