// Local browser QA. Authentication, social RPCs and game APIs are fixtures.
import {createRequire} from 'node:module';import fs from 'node:fs';import {fileURLToPath} from 'node:url';
const repo=fileURLToPath(new URL('../',import.meta.url)),output=process.env.CHS_QA_OUTPUT||'/tmp/chs-design-qa';

const require=createRequire(import.meta.url),{chromium}=require(process.env.CHS_QA_PLAYWRIGHT||'playwright');
const http=require('node:http'),localServer=http.createServer(require(repo+'server').handler);await new Promise(r=>localServer.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+localServer.address().port;
const browser=await chromium.launch({executablePath:process.env.CHS_QA_CHROMIUM||undefined,args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});
fs.mkdirSync(output,{recursive:true});let checks=0;
const stub=`window.supabase={createClient(){const user={id:'11111111-1111-4111-8111-111111111111',email:'qa@example.invalid',user_metadata:{chs_appearance:{collection:'realistic',gender:'male',hair:0,top:0,pants:1}}};window.qaRows=[{peer_id:'peer-a',request_id:'friend-a',username:'Lea <test>',player_tag:'LEA',level:3,status:'accepted',incoming:false,avatar_url:'https://fixture.invalid/lea.webp',online:true,unread_count:1},{peer_id:'peer-b',request_id:'friend-b',username:'Ben',player_tag:'BEN',level:2,status:'pending',incoming:true,avatar_url:'https://fixture.invalid/ben.webp',unread_count:0}];window.qaRead=[];const profile={id:user.id,username:'Elias',player_tag:'EP',level:12,xp:320,rounds_played:28,wins:16,finds:4,survived_rounds:9,active_vehicle_id:'car-a'};return {auth:{getSession:async()=>({data:{session:{user,access_token:'qa-token'}}}),onAuthStateChange:()=>{},updateUser:async()=>({data:{user}})},storage:{from:()=>({getPublicUrl:()=>({data:{publicUrl:''}})})},from(table){let single=false;const q=new Proxy({},{get(_,key){if(key==='then')return resolve=>resolve({data:table==='profiles'?profile:table==='vehicles'?[{id:'car-a',brand:'BMW',model:'328i',model_year:1996,series:'E36',body_type:'Coupé',color:'Madeira Violett',is_active:true}]:[],error:null});if(key==='single'||key==='maybeSingle')return ()=>{single=true;return q};return ()=>q;}});return q;},rpc:async(name,args)=>{if(name==='chs_social_overview_v2')return {data:JSON.parse(JSON.stringify(qaRows))};if(name==='chs_get_messages')return {data:[{message_id:'message-a',sender_id:'peer-a',body:'Hallo Elias!',sent_at:new Date().toISOString()}]};if(name==='chs_mark_messages_read'){qaRead.push(args);qaRows[0].unread_count=0;return {data:null}};return {data:[]}}}}};`;
for(const width of [390,360,430,1000]){const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/supabase-js@2',route=>route.fulfill({contentType:'text/javascript',body:stub}));await page.route('https://fixture.invalid/**',route=>route.fulfill({contentType:'image/webp',body:fs.readFileSync(repo+'assets/'+(route.request().url().endsWith('car.webp')?'vehicle-lineup.webp':'characters/noedge/female/base.webp'))}));await page.route('**/api/**',route=>{const action=new URL(route.request().url()).pathname.split('/').pop();return route.fulfill({json:action==='account-status'?{admin:false,banned:false,accepted:true,legal:{ready:true},onboardingRequired:false}:action==='rejoin-lookup'?{code:null}:action==='invites'?{invites:[]}:action==='personal-stats'?{seekerRounds:5,hiderRounds:23,averageSurvivalSeconds:250}:{ok:true}});});
 await page.goto(base,{waitUntil:'networkidle'});await page.waitForFunction(()=>document.getElementById('homeGreeting').textContent.includes('Elias'));await page.waitForFunction(()=>document.querySelector('#bottomNav [data-page=friends] [data-count-badge]')?.textContent==='2');
 if(errors.length)throw Error('Page errors '+errors.join(';'));if(await page.locator('body').evaluate(e=>e.scrollWidth>innerWidth+2))throw Error('Home overflow '+width);if(await page.locator('#homeOwnScene .lobbyCrewCharacter').count()!==1)throw Error('Own character');checks+=3;await page.screenshot({path:output+'/home-'+width+'.png',fullPage:true});
 if(width===390){
  await page.locator('#homeNotificationButton').click();if(!await page.locator('#notificationsDialog').isVisible())throw Error('Bell dialog');if(!await page.locator('#home').isVisible())throw Error('Bell navigated to crew');if(await page.locator('#notificationsDialog .socialAvatar img').count()!==2)throw Error('Notification identity');if(await page.evaluate(()=>qaRead.length)!==0)throw Error('Bell marked chat read');if(await page.locator('#bottomNav [data-page=friends] [data-count-badge]').textContent()!=='2')throw Error('Bell reset crew badge');await page.screenshot({path:output+'/notifications-390.png'});await page.locator('#notificationsDialog .dialogClose').click();checks+=5;
  await page.evaluate(()=>{communityUI.watchInvites([{id:'qa-invite',code:'QA123',fromName:'Lea',fromAvatarUrl:'https://fixture.invalid/lea.webp',fromOnline:true,lobbyName:'Night Crew',players:3,maxPlayers:8}]);});if(!(await page.locator('#homeFeaturedCard').textContent()).includes('Lea lädt dich ein'))throw Error('Invite priority');if(await page.locator('#homeFeaturedCard .socialAvatar img').count()!==1)throw Error('Invite avatar');checks+=2;await page.screenshot({path:output+'/home-invite-390.png',fullPage:true});
  await page.evaluate(()=>{communityUI.watchInvites([]);});await page.locator('#homeCodeJoin').click();if(!await page.locator('#play #code').isVisible())throw Error('Code real view');checks++;await page.evaluate(()=>openPage('home'));
  const paint=await page.evaluate(async atlas=>{
   const original=vehicleCatalog.illustration;let results=[];
   try{for(let index=0;index<12;index++){
    const x=(index%4)*384,y=index<4?54:index<8?374:687;vehicleCatalog.illustration=()=>({index,x,y,label:'QA'});
    const pixels=async color=>{const html=vehicleIllustration({color}),div=document.createElement('div');div.innerHTML=html;let svg=div.querySelector('svg');svg.setAttribute('xmlns','http://www.w3.org/2000/svg');svg.setAttribute('width','384');svg.setAttribute('height','280');svg.querySelectorAll('image').forEach(i=>i.setAttribute('href',atlas));const img=new Image();img.src='data:image/svg+xml;base64,'+btoa(new XMLSerializer().serializeToString(svg));await img.decode();const c=document.createElement('canvas');c.width=384;c.height=280;const cx=c.getContext('2d');cx.drawImage(img,0,0);return {cx,data:cx.getImageData(0,0,384,280).data};};
    const a=await pixels('Silber'),b=await pixels('Blau'),mask=new Path2D(vehiclePaint.path(index));let painted=0,outside=0;const samples=[];
    for(let yy=0;yy<280;yy++)for(let xx=0;xx<384;xx++){const offset=(yy*384+xx)*4,d=Math.max(...[0,1,2,3].map(k=>Math.abs(a.data[offset+k]-b.data[offset+k])));if(d>3){if(!a.cx.isPointInPath(mask,xx+.5,yy+.5))painted++;else if([-2,-1,0,1,2].every(dx=>[-2,-1,0,1,2].every(dy=>a.cx.isPointInPath(mask,xx+.5+dx,yy+.5+dy)))){outside++;if(samples.length<5)samples.push({x:xx,y:yy,d});}}}
    results.push({index,painted,outside,samples});
   }}finally{vehicleCatalog.illustration=original;}return results;
  },'data:image/webp;base64,'+fs.readFileSync(repo+'assets/vehicle-lineup.webp').toString('base64'));
  if(paint.some(p=>p.painted<300||p.outside>0))throw Error('Paint separation (allowing 2px rasterized mask edges) '+JSON.stringify(paint));console.log('Paint panels '+JSON.stringify(paint));checks+=12;
 }
 await page.locator('#bottomNav [data-page=friends]').click();await page.waitForTimeout(150);if(await page.locator('#friendList .socialAvatar img').count()!==1)throw Error('Avatar absent');if(await page.locator('#incomingFriendNotice').isVisible())throw Error('Notice overlaps friends');if((await page.locator('#friendList .socialPerson strong').textContent())!=='Lea <test>')throw Error('Identity text');checks+=3;await page.screenshot({path:output+'/friends-'+width+'.png',fullPage:true});
 await page.locator('#friendList [data-dm="peer-a"]').click();await page.waitForFunction(()=>window.qaRead.length>0,{timeout:9000});await page.waitForFunction(()=>document.querySelector('#bottomNav [data-page=friends] [data-count-badge]')?.textContent==='1');checks+=2;
 await page.locator('#bottomNav [data-page=profile]').click();await page.screenshot({path:output+'/profile-'+width+'.png',fullPage:true});if(width===390){
 if(await page.locator('.appHeader').isVisible())throw Error('Profile full bleed header');
 await page.locator('#communityShareFriends').click();if(!(await page.locator('#personalInviteLink').inputValue()).includes('friend=11111111-1111-4111-8111-111111111111'))throw Error('Personal invite target');await page.locator('#shareFriendsDialog .dialogClose').click();
 await page.locator('[data-crew-profile=peer-a]').click();if(!await page.locator('#crewProfileDialog .socialAvatar img').isVisible())throw Error('Compact crew profile');await page.locator('#crewProfileDialog .dialogClose').click();
 await page.evaluate(()=>{achievementCatalog=[{id:'FIRST_GAME',name:'Erste Runde',description:'Eine Runde abschließen.',xp_reward:10},{id:'FIRST_FIND',name:'Spürnase',description:'Ein bestätigter Fund.',xp_reward:10},{id:'HIDE_MASTER',name:'Unsichtbar',description:'Als Verstecker überleben.',xp_reward:10}];achievementUnlocked=new Set(['FIRST_GAME']);renderAchievements();});
 await page.locator('[data-achievement=FIRST_FIND]').click();if(!(await page.locator('#badgeDetailsDialog').textContent()).includes('Fortschritt: 1 / 1'))throw Error('Badge real progress');if(!(await page.locator('#badgeDetailsDialog').textContent()).includes('Noch gesperrt'))throw Error('Invented badge unlock');await page.locator('#badgeDetailsDialog .dialogClose').click();checks+=5;await page.screenshot({path:output+'/profile-badges-390.png',fullPage:true});}
 await page.locator('#bottomNav [data-page=garage]').click();await page.screenshot({path:output+'/garage-'+width+'.png',fullPage:true});
 for(const count of [2,5,10]){await page.evaluate(count=>{clearTimeout(pollTimer);const players=Array.from({length:count},(_,i)=>({id:'p'+i,profileId:'a'+i,avatarUrl:i===1?'https://fixture.invalid/lea.webp':'',name:i===0?'Elias':['Lea','Ben','Noah','Mia'][((i-1)%4)],vehicle:'BMW 328i',color:i%2?'Blau':'Madeira Violett',bodyType:'Coupé',connected:true,ready:i<count-1,hasLocation:true,level:12,appearance:{collection:'realistic',gender:i%2?'female':'male',hair:i%3,top:0,pants:1}}));state={serverTime:Date.now(),lobby:{code:'QA123',name:'Elias’ Lobby',hostId:'p0',players,me:players[0],state:'LOBBY',background:'violet',radius:500,settings:{radius:500,duration:900,headstart:120,escape:10}},chat:[],blocksForMe:[]};openPage('game');renderGame();},count);await page.screenshot({path:output+'/lobby-'+count+'-'+width+'.png',fullPage:true});if(await page.locator('#players .parkingPlayer').count()!==count)throw Error('Missing participant');if(await page.locator('#players .freshCrewLead').count()!==1)throw Error('Host missing');if(!await page.locator('#start').isDisabled())throw Error('Unready crew can start');checks+=3;}
 if(width===390){
 if(await page.locator('#communityAdminLab').isVisible())throw Error('Normal admin controls');
 await page.evaluate(()=>{state.lobby.me=state.lobby.players[1];renderGame();});if(!(await page.locator('.freshCrewLead .parkingNameplate').textContent()).includes('Elias'))throw Error('Host foreground');if(!await page.locator('.freshCrewLead .parkingHostBadge').count())throw Error('Missing host crown');if(!await page.locator('#communityVisibility').isDisabled())throw Error('Nonhost privacy editor');
 await page.evaluate(()=>{state.lobby.me=state.lobby.players[0];state.adminTestAvailable=true;state.lobby.players=state.lobby.players.slice(0,1);state.lobby.visibility='PRIVATE';state.lobby.settings.maxPlayers=8;renderGame();});if(!await page.locator('[data-lab=start]').isEnabled())throw Error('Trusted admin solo control');await page.screenshot({path:output+'/admin-solo-390.png',fullPage:true});
 await page.evaluate(()=>{state.lobby.players=Array.from({length:10},(_,i)=>({...state.lobby.players[0],id:'p'+i,name:i?'QA '+i:'Elias'}));state.lobby.hostId='p0';state.lobby.me=state.lobby.players[0];state.adminTestAvailable=false;renderGame();});checks+=5;
 }
 await page.evaluate(()=>{state.lobby.players.forEach(p=>p.ready=true);renderGame();});if(await page.locator('#start').isDisabled())throw Error('Ready crew cannot start');checks++;
 if(width===390){await page.evaluate(()=>{const stage=document.querySelector('.parkingViewport');stage.scrollIntoView({block:'center',behavior:'instant'});});await page.waitForTimeout(500);const covered=await page.locator('#players .parkingNameplate').evaluateAll(nodes=>nodes.filter(n=>{const b=n.getBoundingClientRect();if(b.left<0||b.right>innerWidth||b.top<0||b.bottom>innerHeight)return false;const hit=document.elementFromPoint(b.left+b.width/2,b.top+b.height/2);return !n.contains(hit);}).map(n=>{const b=n.getBoundingClientRect(),hit=document.elementFromPoint(b.left+b.width/2,b.top+b.height/2);return {name:n.textContent,top:b.top,hit:hit?.outerHTML.slice(0,180)};}));if(covered.length){await page.screenshot({path:output+'/covered-diagnostic.png'});throw Error('Covered identities '+JSON.stringify(covered));}checks++;}
 for(const phase of ['HEADSTART','ACTIVE','RESULT']){await page.evaluate(phase=>{state.lobby.state=phase;state.lobby.me.role='SEEKER';state.lobby.players.slice(1).forEach(p=>p.role='HIDER');state.lobby.headstartEndsAt=Date.now()+90000;state.lobby.endsAt=Date.now()+600000;state.lobby.result={seekersWin:false,found:1,totalHiders:9,players:state.lobby.players.map((p,i)=>({...p,foundBy:i===1?'p0':null,finds:i===0?1:0,survivalSeconds:120,baseXp:15}))};localStorage.setItem('chsRulesSeen:a0','true');renderGame();},phase);await page.screenshot({path:output+'/'+phase.toLowerCase()+'-'+width+'.png',fullPage:true});if(phase==='HEADSTART'&&!(await page.locator('#gameplayDetails').textContent()).includes('Beobachte nicht'))throw Error('Seeker headstart rule');if(phase==='ACTIVE'&&!await page.locator('#targets').isVisible())throw Error('No target controls');if(phase==='RESULT'&&!(await page.locator('.gameplayResults').textContent()).includes('Elias'))throw Error('Result identity');checks++;if(phase==='HEADSTART'){await page.evaluate(()=>{state.lobby.me.role='HIDER';renderGame();});if(!(await page.locator('#gameplayDetails').textContent()).includes('Versteck dich im Spielgebiet'))throw Error('Hider headstart hint');await page.screenshot({path:output+'/headstart-hider-'+width+'.png',fullPage:true});checks++;}}
 await page.evaluate(()=>{openPage('garage');openCarModal();pendingCarPhoto='https://fixture.invalid/car.webp';window.referenceUI.renderPhotoPreview();});if(await page.locator('#photoLobbyPreview img').count()<1)throw Error('Photo preview missing');await page.evaluate(()=>{pendingCarPhoto='';window.referenceUI.renderPhotoPreview();});if(await page.locator('#photoLobbyPreview').isVisible())throw Error('Stale photo preview');await page.evaluate(()=>{pendingCarPhoto='https://fixture.invalid/car.webp';window.referenceUI.renderPhotoPreview();});if(await page.locator('#photoLobbyPreview img').count()<1)throw Error('Repeated photo preview missing');await page.waitForFunction(()=>document.querySelector('#photoLobbyPreview .lobbyModelCar')?.naturalWidth>0);checks++;await page.locator('#photoLobbyPreview').scrollIntoViewIfNeeded();await page.screenshot({path:output+'/photo-'+width+'.png',fullPage:true});checks+=3;
 if(errors.length)throw Error('Errors '+errors.join(';'));await page.close();}
// A new, non-admin user must see an actionable beta gate, not a retry loop.
{
 const page=await browser.newPage({viewport:{width:390,height:900}}),legal=require(repo+'legal').documents({CHS_BETA_ACCESS:'true'});let accepted=false,acceptCalls=0;const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/supabase-js@2',r=>r.fulfill({contentType:'text/javascript',body:stub}));
 await page.route('https://fixture.invalid/**',r=>r.fulfill({contentType:'image/webp',body:fs.readFileSync(repo+'assets/characters/noedge/female/base.webp')}));
 await page.route('**/api/**',r=>{const action=new URL(r.request().url()).pathname.split('/').pop();if(action==='legal-accept'){const data=r.request().postDataJSON();if(data.version!==legal.version||data.hash!==legal.hash||!['terms','safety','adult','privacyRead'].every(k=>data[k]===true))throw Error('Invalid beta acceptance payload');acceptCalls++;accepted=true;}return r.fulfill({json:action==='account-status'?{admin:false,banned:false,accepted,legal,onboardingRequired:false}:action==='rejoin-lookup'?{code:null}:action==='invites'?{invites:[]}:action==='personal-stats'?{}:{ok:true}});});
 await page.goto(base,{waitUntil:'networkidle'});await page.locator('#accountGate').waitFor({state:'visible'});
 if(await page.locator('#accountGate [data-account-retry]').count())throw Error('Beta retry loop');
 if(!(await page.locator('#accountGate').textContent()).includes('Vorläufiger Beta-Test'))throw Error('Missing beta notice');
 await page.locator('#accountGate button[type=submit]').click();if(acceptCalls!==0)throw Error('Accepted unchecked consent');
 for(const name of ['terms','safety','adult','privacyRead'])await page.locator('#accountGate input[name='+name+']').check();
 await page.locator('#accountGate button[type=submit]').click();await page.waitForFunction(()=>document.getElementById('app')?.classList.contains('hidden')===false&&document.getElementById('accountGate')===null);
 if(acceptCalls!==1)throw Error('Beta acceptance lost or duplicated');await page.reload({waitUntil:'networkidle'});if(await page.locator('#accountGate').count())throw Error('Acceptance not recovered');if(await page.locator('#adminMenuButton').isVisible())throw Error('Beta grants admin');if(errors.length)throw Error(errors.join(';'));checks+=7;await page.close();
}
console.log(JSON.stringify({checks,widths:[360,390,430,1000],scope:'Actual frontend with local auth/API fixtures; no real messages sent; no physical GPS or external map-tile validation',screenshots:output}));await browser.close();await new Promise(r=>localServer.close(r));
