const {PGlite}=await import(process.argv[3]||'@electric-sql/pglite');
import fs from 'node:fs';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema chs_private;
create table auth.users(id uuid primary key);create table public.profiles(id uuid primary key references auth.users(id));
create table public.chs_account_bans(user_id uuid primary key references auth.users(id),reason text,until_at timestamptz,revoked_at timestamptz,updated_at timestamptz);
create table public.chs_admin_audit(id uuid primary key default gen_random_uuid(),actor_id uuid references auth.users(id) on delete set null,target_id uuid references auth.users(id) on delete set null,action text constraint chs_admin_audit_action_check check(action in ('BAN','UNBAN')),reason text,created_at timestamptz default now());
create table public.chs_server_state(slot text primary key,snapshot jsonb,expires_at timestamptz);
grant all on public.profiles,public.chs_account_bans,public.chs_admin_audit,public.chs_server_state to service_role;`);
let sql=fs.readFileSync(process.argv[2],'utf8');sql=sql.slice(0,sql.indexOf('-- Database scheduling'));
await db.exec(sql);
await db.exec(fs.readFileSync(process.argv[2].replace('20261001112512_moderation_roles_beta.sql','20261001115940_beta_metric_deleted_accounts.sql'),'utf8'));
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',c='33333333-3333-4333-8333-333333333333';
await db.exec(`insert into auth.users values('${a}'),('${b}'),('${c}');insert into profiles select id from auth.users;insert into chs_staff_roles values('${a}','super_admin',now()),('${b}','moderator',now());set role service_role;`);
let count=0;
async function rejects(sql){try{await db.exec(sql);
await db.exec(fs.readFileSync(process.argv[2].replace('20261001112512_moderation_roles_beta.sql','20261001115940_beta_metric_deleted_accounts.sql'),'utf8'));throw Error('Unexpected authorization');}catch(e){if(e.message==='Unexpected authorization')throw e;count++;}}
await rejects(`select chs_admin_set_role('${b}','${c}','admin','Test reason')`);
await rejects(`select chs_admin_set_role('${a}','${a}','user','Test reason')`);
await db.exec(`select chs_admin_set_role('${a}','${c}','admin','Test reason')`);count++;
await rejects(`select chs_admin_set_ban('${c}','${a}','Test reason',null,false)`);
const report='44444444-4444-4444-8444-444444444444';await db.exec(`insert into chs_player_reports(id,reporter_id,target_id,lobby_code,category) values('${report}','${b}','${c}','ABCDE','other')`);
const revision=(await db.query(`select updated_at::text as revision from chs_player_reports`)).rows[0].revision;
await db.exec(`select chs_admin_update_report('${b}','${report}','in_review','Test review','${revision}')`);count++;
await rejects(`select chs_admin_update_report('${b}','${report}','resolved','Test review','${revision}')`);
await rejects(`update chs_admin_audit set reason='Forged'`);await rejects(`delete from chs_admin_audit`);
await db.exec(`reset role;set role authenticated;`);await rejects(`select * from chs_staff_roles`);await rejects(`select chs_admin_beta_stats('${a}')`);
await db.exec('reset role');await db.exec(`insert into chs_server_state values('gameplay','{"lobbies":[{"location":{"lat":52}}]}',now()-interval '1 hour');select chs_beta_retention()`);
if((await db.query('select snapshot from chs_server_state')).rows[0].snapshot.lobbies.length)throw Error('GPS retention failed');count++;
const match={result_id:'55555555-5555-4555-8555-555555555555',lobby_code:'ABCDE',started_at:'2026-10-01T00:00:00Z',ended_at:'2026-10-01T00:05:00Z',duration_seconds:300,player_count:2,visibility:'PRIVATE',aborted:false,reason:'TIME'};
const participants=[{user_id:a,role:'HIDER',finds:0,survival_seconds:300,won:true},{user_id:'66666666-6666-4666-8666-666666666666',role:'SEEKER',finds:0,survival_seconds:300,won:false}];
await db.query('select chs_record_match($1::jsonb,$2::jsonb)',[JSON.stringify(match),JSON.stringify(participants)]);
await db.query('select chs_record_match($1::jsonb,$2::jsonb)',[JSON.stringify(match),JSON.stringify(participants)]);
if(Number((await db.query('select count(*) as count from chs_match_metrics')).rows[0].count)!==1)throw Error('Duplicate match');
if(Number((await db.query('select count(*) as count from chs_player_round_stats')).rows[0].count)!==1)throw Error('Deleted user blocked match');count+=2;
console.log(JSON.stringify({sqlChecks:count,migration:'passed',cron:'excluded from local WASM; verify after apply'}));await db.close();
