// Local browser QA. Authentication, social RPCs and game APIs are fixtures.
import {createRequire} from 'node:module';import fs from 'node:fs';import {fileURLToPath} from 'node:url';
const repo=fileURLToPath(new URL('../',import.meta.url)),output=process.env.CHS_QA_OUTPUT||'/tmp/chs-design-qa';

const require=createRequire(import.meta.url),{chromium}=require(process.env.CHS_QA_PLAYWRIGHT||'playwright');
const http=require('node:http'),localServer=http.createServer(require(repo+'server').handler);await new Promise(r=>localServer.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+localServer.address().port;
const browser=await chromium.launch({executablePath:process.env.CHS_QA_CHROMIUM||undefined,args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});
fs.mkdirSync(output,{recursive:true});let checks=0;
const stub=`window.supabase={createClient(){const user={id:'11111111-1111-4111-8111-111111111111',email:'qa@example.invalid',user_metadata:{chs_appearance:{collection:'realistic',gender:'male',hair:0,top:0,pants:1}}};window.qaRows=[{peer_id:'peer-a',request_id:'friend-a',username:'Lea <test>',player_tag:'LEA',level:3,status:'accepted',incoming:false,avatar_url:'https://fixture.invalid/lea.webp',online:true,unread_count:1},{peer_id:'peer-b',request_id:'friend-b',username:'Ben',player_tag:'BEN',level:2,status:'pending',incoming:true,avatar_url:'https://fixture.invalid/ben.webp',unread_count:0}];window.qaRead=[];const profile={id:user.id,username:'Elias',player_tag:'EP',level:12,xp:320,rounds_played:28,wins:16,finds:4,survived_rounds:9,active_vehicle_id:'car-a'};return {auth:{getSession:async()=>({data:{session:{user,access_token:'qa-token'}}}),onAuthStateChange:()=>{},updateUser:async()=>({data:{user}})},storage:{from:()=>({getPublicUrl:()=>({data:{publicUrl:''}})})},from(table){let single=false;const q=new Proxy({},{get(_,key){if(key==='then')return resolve=>resolve({data:table==='profiles'?profile:table==='vehicles'?[{id:'car-a',brand:'BMW',model:'328i',model_year:1996,series:'E36',body_type:'Coupé',color:'Madeira Violett',is_active:true}]:[],error:null});if(key==='single'||key==='maybeSingle')return ()=>{single=true;return q};return ()=>q;}});return q;},rpc:async(name,args)=>{if(name==='chs_social_overview_v2')return {data:JSON.parse(JSON.stringify(qaRows))};if(name==='chs_get_messages')return {data:[{message_id:'message-a',sender_id:'peer-a',body:'Hallo Elias!',sent_at:new Date().toISOString()}]};if(name==='chs_mark_messages_read'){qaRead.push(args);qaRows[0].unread_count=0;return {data:null}};return {data:[]}}}}};`;
for(const width of [390,360,430,1000]){const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/supabase-js@2',route=>route.fulfill({contentType:'text/javascript',body:stub}));await page.route('https://fixture.invalid/**',route=>route.fulfill({contentType:'image/webp',body:fs.readFileSync(repo+'assets/'+(route.request().url().endsWith('car.webp')?'vehicle-lineup.webp':'characters/noedge/female/base.webp'))}));await page.route('**/api/**',route=>{const action=new URL(route.request().url()).pathname.split('/').pop();return route.fulfill({json:action==='account-status'?{admin:false,banned:false,accepted:true,legal:{ready:true},onboardingRequired:false}:action==='rejoin-lookup'?{code:null}:action==='invites'?{invites:[]}:action==='personal-stats'?{seekerRounds:5,hiderRounds:23,averageSurvivalSeconds:250}:{ok:true}});});
 await page.goto(base,{waitUntil:'networkidle'});await page.waitForFunction(()=>document.getElementById('homeGreeting').textContent.includes('Elias'));await page.waitForFunction(()=>document.querySelector('#bottomNav [data-page=friends] [data-count-badge]')?.textContent==='2');
 if(errors.length)throw Error('Page errors '+errors.join(';'));if(await page.locator('body').evaluate(e=>e.scrollWidth>innerWidth+2))throw Error('Home overflow '+width);if(await page.locator('#homeOwnScene .lobbyCrewCharacter').count()!==1)throw Error('Own character');checks+=3;await page.screenshot({path:output+'/home-'+width+'.png',fullPage:true});
 await page.locator('#bottomNav [data-page=friends]').click();await page.waitForTimeout(150);if(await page.locator('#friendList .socialAvatar img').count()!==1)throw Error('Avatar absent');if(await page.locator('#incomingFriendNotice').isVisible())throw Error('Notice overlaps friends');if((await page.locator('#friendList .socialPerson strong').textContent())!=='Lea <test>')throw Error('Identity text');checks+=3;await page.screenshot({path:output+'/friends-'+width+'.png',fullPage:true});
 await page.locator('#friendList [data-dm="peer-a"]').click();await page.waitForFunction(()=>window.qaRead.length>0,{timeout:9000});await page.waitForFunction(()=>document.querySelector('#bottomNav [data-page=friends] [data-count-badge]')?.textContent==='1');checks+=2;
 await page.locator('#bottomNav [data-page=profile]').click();await page.screenshot({path:output+'/profile-'+width+'.png',fullPage:true});await page.locator('#bottomNav [data-page=garage]').click();await page.screenshot({path:output+'/garage-'+width+'.png',fullPage:true});
 for(const count of [2,5,10]){await page.evaluate(count=>{clearTimeout(pollTimer);const players=Array.from({length:count},(_,i)=>({id:'p'+i,profileId:'a'+i,avatarUrl:i===1?'https://fixture.invalid/lea.webp':'',name:i===0?'Elias':['Lea','Ben','Noah','Mia'][((i-1)%4)],vehicle:'BMW 328i',color:i%2?'Blau':'Madeira Violett',bodyType:'Coupé',connected:true,ready:i<count-1,hasLocation:true,level:12,appearance:{collection:'realistic',gender:i%2?'female':'male',hair:i%3,top:0,pants:1}}));state={serverTime:Date.now(),lobby:{code:'QA123',name:'Elias’ Lobby',hostId:'p0',players,me:players[0],state:'LOBBY',background:'violet',radius:500,settings:{radius:500,duration:900,headstart:120,escape:10}},chat:[],blocksForMe:[]};openPage('game');renderGame();},count);await page.screenshot({path:output+'/lobby-'+count+'-'+width+'.png',fullPage:true});if(await page.locator('#players .parkingPlayer').count()!==count)throw Error('Missing participant');if(await page.locator('#players .freshCrewLead').count()!==1)throw Error('Host missing');if(!await page.locator('#start').isDisabled())throw Error('Unready crew can start');checks+=3;}
 await page.evaluate(()=>{state.lobby.players.forEach(p=>p.ready=true);renderGame();});if(await page.locator('#start').isDisabled())throw Error('Ready crew cannot start');checks++;
 if(width===390){await page.evaluate(()=>{const stage=document.querySelector('.parkingViewport');stage.scrollIntoView({block:'center'});});await page.waitForTimeout(150);const covered=await page.locator('#players .parkingNameplate').evaluateAll(nodes=>nodes.filter(n=>{const b=n.getBoundingClientRect();if(b.left<0||b.right>innerWidth)return false;const hit=document.elementFromPoint(b.left+b.width/2,b.top+b.height/2);return !n.contains(hit);}).map(n=>n.textContent));if(covered.length)throw Error('Covered identities '+covered);checks++;}
 for(const phase of ['HEADSTART','ACTIVE','RESULT']){await page.evaluate(phase=>{state.lobby.state=phase;state.lobby.me.role='SEEKER';state.lobby.players.slice(1).forEach(p=>p.role='HIDER');state.lobby.headstartEndsAt=Date.now()+90000;state.lobby.endsAt=Date.now()+600000;state.lobby.result={seekersWin:false,found:1,totalHiders:9,players:state.lobby.players.map((p,i)=>({...p,foundBy:i===1?'p0':null,finds:i===0?1:0,survivalSeconds:120,baseXp:15}))};localStorage.setItem('chsRulesSeen:a0','true');renderGame();},phase);await page.screenshot({path:output+'/'+phase.toLowerCase()+'-'+width+'.png',fullPage:true});if(phase==='HEADSTART'&&!(await page.locator('#gameplayDetails').textContent()).includes('Beobachte nicht'))throw Error('Seeker headstart rule');if(phase==='ACTIVE'&&!await page.locator('#targets').isVisible())throw Error('No target controls');if(phase==='RESULT'&&!(await page.locator('.gameplayResults').textContent()).includes('Elias'))throw Error('Result identity');checks++;if(phase==='HEADSTART'){await page.evaluate(()=>{state.lobby.me.role='HIDER';renderGame();});if(!(await page.locator('#gameplayDetails').textContent()).includes('Versteck dich im Spielgebiet'))throw Error('Hider headstart hint');await page.screenshot({path:output+'/headstart-hider-'+width+'.png',fullPage:true});checks++;}}
 await page.evaluate(()=>{openPage('garage');openCarModal();pendingCarPhoto='https://fixture.invalid/car.webp';window.referenceUI.renderPhotoPreview();});if(await page.locator('#photoLobbyPreview img').count()<1)throw Error('Photo preview missing');await page.evaluate(()=>{pendingCarPhoto='';window.referenceUI.renderPhotoPreview();});if(await page.locator('#photoLobbyPreview').isVisible())throw Error('Stale photo preview');await page.evaluate(()=>{pendingCarPhoto='https://fixture.invalid/car.webp';window.referenceUI.renderPhotoPreview();});if(await page.locator('#photoLobbyPreview img').count()<1)throw Error('Repeated photo preview missing');await page.waitForFunction(()=>document.querySelector('#photoLobbyPreview .lobbyModelCar')?.naturalWidth>0);checks++;await page.locator('#photoLobbyPreview').scrollIntoViewIfNeeded();await page.screenshot({path:output+'/photo-'+width+'.png',fullPage:true});checks+=3;
 if(errors.length)throw Error('Errors '+errors.join(';'));await page.close();}
console.log(JSON.stringify({checks,widths:[360,390,430,1000],scope:'Actual frontend with local auth/API fixtures; no real messages sent; no physical GPS or external map-tile validation',screenshots:output}));await browser.close();await new Promise(r=>localServer.close(r));
